### ISSUE TITLE
ssl generation...

### ISSUE THREAD

**Issue by athen66** [amzn/alexa-avs-raspberry-pi#10]
so the alexa source 'generate.sh' script pretty much fails when trying to generate the SSL keys...

Product ID: my_device
Serial Number: 123456
Password for Keystores (won't echo): Generating RSA private key, 4096 bit long modulus
...................++
............................................................................................................................................................................................................................................................................................................++
e is 65537 (0x10001)
problems making Certificate Request
1995954272:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2
Generating RSA private key, 2048 bit long modulus
.................................................................+++
......................+++
e is 65537 (0x10001)
problems making Certificate Request
1995810912:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2
certs/client/client.csr: No such file or directory
Error opening input file certs/client/client.crt
certs/client/client.crt: No such file or directory
Generating RSA private key, 2048 bit long modulus
...........+++
...............................................................................................................................................................................................................+++
e is 65537 (0x10001)
problems making Certificate Request
1996130400:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2
certs/server/node.csr: No such file or directory
Generating RSA private key, 2048 bit long modulus
..................................................+++
...................+++
e is 65537 (0x10001)
problems making Certificate Request
1995569248:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2
certs/server/jetty.csr: No such file or directory
Error opening input file certs/server/jetty.crt
certs/server/jetty.crt: No such file or directory
cp: cannot stat 'certs/ca/ca.crt': No such file or directory
Error opening Certificate certs/ca/ca.crt
1996052576:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('certs/ca/ca.crt','r')
1996052576:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
cp: cannot stat 'certs/ca/ca.der': No such file or directory

**Comment by jaysuk** [comment]
I have also had an issue with this.
I was able to generate certs by removing the prompt=no from ssl.conf and answering the questions manually
I have been able to launch the companion service but when launching the java client, it cannot see the companion service. I am not sure whether this is due to ssl cert issue.

**Comment by athen66** [comment]
Ah, you put me on the right track. Didn't notice the ssl.cnf file within that folder (as I was editing /etc/ssl/openssl.cnf)

I adjusted the company name/location/etc. values accordingly and the keys generated without a problem.

**Comment by jaysuk** [comment]
I still have this issue, even when filling out all the info in SSL.cnf
