### ISSUE TITLE
alexa-avs-raspberry-pi npm error 

### ISSUE THREAD

**Issue by SyntaxErrr0r** [amzn/alexa-avs-raspberry-pi#100]
Help please 

> pi@raspberrypi:~/Downloads/alexa-avs-raspberry-pi-master/samples/companionService
$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

> 
> This node service needs to be running to store token information
> memory and vend them for the AVS app.
> 
> 
> fs.js:436
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> Error: ENOENT, no such file or directory
> '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.crt'
>     at Object.fs.openSync (fs.js:436:18)
>     at Object.fs.readFileSync (fs.js:290:15)
>     at Object.<anonymous>
> (/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/companionService/bin/www:22:14)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:906:3
> 
> npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start:
> `node ./bin/www`
> npm ERR! Exit status 8
> npm ERR!
> npm ERR! Failed at the
> alexa-voice-service-sample-companion-service@1.0.0 start script.
> npm ERR! This is most likely a problem with the
> alexa-voice-service-sample-companion-service package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 4.1.19-v7+
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! cwd /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/companionService
> npm ERR! node -v v0.10.29
> npm ERR! npm -v 1.4.21
> npm ERR! code ELIFECYCLE
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
> 
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log
> npm ERR! not ok code 0

npm debug log shows the following 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@1.4.21
> 3 info using node@v0.10.29
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart alexa-voice-service-sample-companion-service@1.0.0
> 6 info start alexa-voice-service-sample-companion-service@1.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to
> exec start script
> 9 error alexa-voice-service-sample-companion-service@1.0.0 start:
> `node ./bin/www`
> 9 error Exit status 8
> 10 error Failed at the
> alexa-voice-service-sample-companion-service@1.0.0 start script.
> 10 error This is most likely a problem with the
> alexa-voice-service-sample-companion-service package,
> 10 error not with npm itself.
> 10 error Tell the author that this fails on your system:
> 10 error     node ./bin/www
> 10 error You can get their info via:
> 10 error     npm owner ls alexa-voice-service-sample-companion-service
> 10 error There is likely additional logging output above.
> 11 error System Linux 4.1.19-v7+
> 12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 13 error cwd /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/companionService
> 14 error node -v v0.10.29
> 15 error npm -v 1.4.21
> 16 error code ELIFECYCLE
> 17 verbose exit [ 1, true ]

My guess is it is the 
> Error: ENOENT, no such file or directory '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.crt' 

but no idea how to fix this because the node.crt file is NOT in my directory or not visible maybe. Any help appreciated. Thanks!

**Comment by danhannigan** [comment]
@SyntaxErrr0r Just want to double check - did you make sure to run steps 3 and 4 above it? Also prior to that, did you set your countryName in the ssl.cnf and if so, is it only two characters?

**Comment by SyntaxErrr0r** [comment]
@danhannigan you sir are great! I had to redo the ssl configuration because countryName was not 2 characters. Thank you so much, greatly appreciated!

**Comment by danhannigan** [comment]
@SyntaxErrr0r glad to hear it's worked out! Be sure to close the ticket out if you're good :+1:

**Comment by Comm4nd0** [comment]
THANK YOU!! i did have two letters for the country but it was YOUR_UK.... so it wasn't really two chars. fixed ;)
