### ISSUE TITLE
Amazon returned error upon registration

### ISSUE THREAD

**Issue by steven-chau** [amzn/alexa-avs-raspberry-pi#101]
Hi Guys,

I followed the instructions almost to the end. When I tried to register my device using the URL
`https://localhost:3000/provision/blahblahblah`

Amazon gave me this error after I logged in and clicked OK:
```
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
 Go to Amazon.com's Home Page
```

What might be the cause? Is there anything I can do to troubleshoot / solve the problem? I don't see anything unusual in the log of the javaclient / companionService...

Thanks in advance.

**Comment by ajotwani** [comment]
@steven-chau have you looked at this thread - https://github.com/amzn/alexa-avs-raspberry-pi/issues/5?

**Comment by steven-chau** [comment]
Thank you @ajotwani 

I made the same mistake as the other guy did:

>Figured it out. You have to make sure the device Id you put into amazon is my_device or it will not work correctly.

**Comment by TheFonix** [comment]
Sorry to open up an old thread but im having the same issue, but i already have the device name set to my_device, as soon as i hit the ok button to get the key from the AlexaPi it shows up with 

We're sorry!
An error occurred when we tried to process your request

Any ideas? Seems nobody else is having this now since the device name fixed it, Ive tried moving the directory i lauch it from, ive tired flashing and putting a new install on rasp on, ive also tried a new amazon account and nothing seems to work.

**Comment by TeamKalis** [comment]
Still having this issue. Both on normal laptop and RASP PI. All of them are My_device. Help!

**Comment by manojcena** [comment]
Hi i also facing the same error while login with amazon but i came to know that i need to add device details. but i am unable to find where to update the device details. can any one help me out to solve the problem.

**Comment by hannan112** [comment]
hi i am facing this problem pls help me
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.

**Comment by hannan112** [comment]
![capture](https://user-images.githubusercontent.com/41451097/43357138-e8cf4c98-9231-11e8-9318-079fa5878716.JPG)
