### ISSUE TITLE
Problems with nodejs and npm install

### ISSUE THREAD

**Issue by Bedour** [amzn/alexa-avs-raspberry-pi#102]
I have installed nodejs following the described instructions, but when I tried to make sure it installed properly by checking the version `node -v` I got (Segmentation fault) error.  The same goes when I try `npm install`. How do I get over this problem?

**Comment by Bedour** [comment]
Well I managed to fix the first part following the instructions here

http://weworkweplay.com/play/raspberry-pi-nodejs/

So `node -v` results in v4.2.1

However I still get segmentation fault with `npm install`. Any help would be appreciated.

**Comment by danhannigan** [comment]
Did you try clearing out the node_modules and running npm install again?

**Comment by Bedour** [comment]
No I did not. However I typed `npm instal` with 1 L by accident and it worked! Thanks for your prompt help, really appreciate it! 
![image](https://cloud.githubusercontent.com/assets/5548810/14290567/6ab1a7e8-fb57-11e5-9c98-4ffb295bc1b9.png)

**Comment by danhannigan** [comment]
Wait... `npm instal` worked but `npm install` didn't? 

Either way: glad it's all working!

**Comment by Bedour** [comment]
I KNOW RIGHT?! It was sheer dumb luck!! I couldn't believe it myself I had to screen grab it. Now I'm sharing it just in case it works for someone else! Thanks for your help!!
