### ISSUE TITLE
Your instructions say to run mvn exec:exec when you should run mvn exec:java

### ISSUE THREAD

**Issue by GusCaplan** [amzn/alexa-avs-raspberry-pi#103]
Like the title says.

**Comment by knfrfd** [comment]
diff --git a/test/test-config.sh b/test/test-config.sh index
b185396..b6438a8 100755 --- a/test/test-config.sh +++ b/test/test-config.sh
@@ -15,12 +15,25 @@ begin_test "default config" git config
--file=.gitconfig lfs.url http://gitconfig-file-ignored git config
--file=.lfsconfig lfs.url http://lfsconfig-file + git config
--file=.lfsconfig lfs.http://lfsconfig-file.access lfsconfig git lfs env |
tee env.log - grep "Endpoint=http://lfsconfig-file (auth=none)" env.log +
grep "Endpoint=http://lfsconfig-file (auth=lfsconfig)" env.log + # new
endpoint url from local git config + # access setting no longer applied git
config lfs.url http://local-lfsconfig git lfs env | tee env.log grep
"Endpoint=http://local-lfsconfig (auth=none)" env.log + + # add the access
setting to lfsconfig + git config --file=.lfsconfig lfs.
http://local-lfsconfig.access lfsconfig + git lfs env | tee env.log + grep
"Endpoint=http://local-lfsconfig (auth=lfsconfig)" env.log + + # add the
access setting to git config¡ + git config lfs.http://local-lfsconfig.access
config + git lfs env | tee env.log + grep "Endpoint=http://local-lfsconfig
(auth=config)" env.log
در تاریخ ۵ آوریل ۲۰۱۶ ۲۲:۳۲، "Gus Caplan" <notifications@github.com> نوشت:

**Comment by cwilkes** [comment]
Does exec:exec not work for you?

**Comment by GusCaplan** [comment]
no, but exec:java does and it shows exec:java in the tutorial ___image___ but not the ___text___.

**Comment by GusCaplan** [comment]
@knfrfd did you throw up into your computer?

**Comment by ajotwani** [comment]
Fixed with https://github.com/amzn/alexa-avs-raspberry-pi/commit/ce59b50f59bce756955df74a4f940520c230bf20.
