### ISSUE TITLE
Voice Remote as button input?

### ISSUE THREAD

**Issue by olliegg123** [amzn/alexa-avs-raspberry-pi#104]
I'm wondering if it's possible to connect the voice remote as you can with the regular Echo. And whether the press of that button would activate the listening, or a way for somebody to make it work like that? Very beginner, so no idea myself.

**Comment by Eddie-Hartman** [comment]
I have been looking into this as well. This would be the thing to make the pi a full time Alexa machine in my home. I am looking into [this](http://pi4j.com/index.html) to see if it would be possible to add the code and watch the GPIO pins for a user action. Preferably it would record as long as you hold the button down and then stop when you let go similar to [this](https://youtu.be/frH9HaQTFL8) which has code available, but in python.

**Comment by joetech** [comment]
@Eddie-Hartman I didn't like the Java implementation as much and want mine to be headless, so I just set up the Sam Machin one in Python.  There's some issues with the setup, but I have it working great in just over an hour with a push button working like you're looking for.  I used the Alexa android app to link it up to my smart home devices and it plays well.  If I can get a voice activated trigger working on it, I'll be all set.

**Comment by joetech** [comment]
@olliegg123 I would imagine that anything you can make your Pi listen for could be used as a remote trigger.

**Comment by olliegg123** [comment]
@Eddie-Hartman That looks pretty much exactly what I was hoping for. Because people already have their hardware buttons working with the GPIO pins. Keep me updated with your progress please!

Also @joetech please keep us all updated on your work with the always listening or this idea. Just anything that can trigger the recording really that is wireless. Just a wireless button would probably be enough.

**Comment by joetech** [comment]
@olliegg123 Have you thought about trying to use an Amazon Dash button?  It works over wifi and seems like it would be a good fit for this type of thing.  As for the audio trigger, reading [this article](http://willdrevo.com/fingerprinting-and-audio-recognition-with-python/) this morning gives me a lot of hope.  Plus, it seems like a lot of the work is already done.

**Comment by olliegg123** [comment]
@joetech I would've loved to try Amazon Dash buttons but I'm in the UK. Having enough trouble with trying to get the Echo Pi to locate itself correctly! And that article sounds very promising!

**Comment by cwilkes** [comment]
Check out https://github.com/amzn/alexa-avs-raspberry-pi/issues/72 for some other ideas. 

I was able to get the clap detector to work somewhat in that when I can the node app it would execute the code in the handler some of the time.  I haven't tried to get that and Alexa to work at the same time.

**Comment by olliegg123** [comment]
@cwilkes That looks great. Hopefully we will have another update sooner. A clap detector would be a good alternative.

**Comment by nitrag** [comment]
What about Pocketsphinx to listen and fire a software trigger?

**Comment by olliegg123** [comment]
@nitrag That looks very interesting. i have no idea how easy it would be to implement it into calling the listening feature. Any idea?

**Comment by nitrag** [comment]
Think they did it here:
http://www.instructables.com/id/Multi-Mic-Speech-To-Text-with-Python/

I'm not sure about the software trigger to this repo's source code though...

**Comment by olliegg123** [comment]
Ah, so if that could be attached to something similar to that in #86 then the co-ordinates could be used to activate a click in that location when it heard a clap or 'Alexa' for example. I wouldn't have any idea where to start though...

**Comment by Magerk** [comment]
Just finished building alexa with raspberry pi-3 and was looking at
 http://diyhacking.com/best-voice-recognition-software-for-raspberry-pi/
to try and combine it with alexa. Has anyone else had any luck avoiding the push to talk?

**Comment by Eddie-Hartman** [comment]
@Magerk This guy is working on it. https://github.com/jbyttow/alexa-avs-raspberry-pi

**Comment by Ikol18** [comment]
Guys please help
Everything is setup perfectly with oracle java 8, maven ,node and everything
When I click on start listening the bar indicates its listening but when I press stop its not giving output
please help me
useful info:
using rpi2
usb sound card with mic input and speaker output(both are in working condition)
node v 5.10.0 and npm v3.8.3

**Comment by ajotwani** [comment]
Last comment from @Ikol18 same as https://github.com/amzn/alexa-avs-raspberry-pi/issues/166#issuecomment-215519219.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
