### ISSUE TITLE
Any suggestions?

### ISSUE THREAD

**Issue by mjt85nc** [amzn/alexa-avs-raspberry-pi#105]
I have two pi's. The one has berryboot with raspbian/retropie/openelec. I got Alexa running perfectly on it. The second has a tripleboot build raspbian/retropie/kodi. Everything is up and running I'm connected on npm start it's listening and I ran mvn exec:exec connected entering https://local host:3000/provision/......  When I click it beeps but won't record my voice. I'm using same mic as the other pi I have and it works great. Any clue what could be the problem?

**Comment by cwilkes** [comment]
I followed the steps at http://www.voxforge.org/home/docs/faq/faq/linux-how-to-determine-your-audio-cards-or-usb-mics-maximum-sampling-rate to see what my microphone can do. 
I would imagine that has to work before Alexa can work. Give that a shot.

**Comment by mjt85nc** [comment]
I got it to work I had to reinstall pulseaudio and pavucontrol. Thanks

**Comment by ajotwani** [comment]
Per confirmation from @mjt85nc, closing as fixed.
