### ISSUE TITLE
npm install > Segmentation fault

### ISSUE THREAD

**Issue by David6409** [amzn/alexa-avs-raspberry-pi#106]
Hello everyone,
When I try `npm install`, it shows this message `Segmentation fault`. Is there any way to solve this?

Thanks.

**Comment by cwilkes** [comment]
That sounds like you have a copy of node compiled for a different architecture (CPU). Are you using a pi2 or pi3?  What version of Debian (Jessie or Wheezy)?  How did you install node?

**Comment by David6409** [comment]
Hi cwilkes,
I'm trying with a pi1 for this project, maybe this is why it won't work. I use Debian Jessie. I don't think I have install node, I just following the step on the README.md. Is the problem only show on the pi1?

Thank you.

**Comment by gabyquiles** [comment]
I had the same problem and ended uninstalling nodejs and then compiling a newer version. I found this script and just updated the version and it is working fine so far. I'm running a Pi 1 also.
https://gist.github.com/chj1axr0/8d356a38a44ea595c2c1

**Comment by David6409** [comment]
Thanks gabyquiles!
 I'll try it out.

**Comment by pygold** [comment]
I also faced this problem in raspberry pi B+. I simply changed the apt-get repo source from
**curl -sL https://deb.nodesource.com/setup | sudo bash -**
to
**curl -sLS https://apt.adafruit.com/add | sudo bash**
After that running **sudo apt-get install node** installed nodejs successfully.

You can follow the link below for more information.
https://learn.adafruit.com/node-embedded-development/installing-node-dot-js

**Comment by olsonk** [comment]
@TheNuttyMaker that also fixed the issue I'd encountered with the Segmentation Fault error. Getting a proper version of NodeJS for the Pi 1 (and Pi Zero) took care of things, and Adafruit's repo had the version I needed.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by XP1** [comment]
The repo scripts support ARMv7 and higher. Raspbery Pi 1 is ARMv6, so the repo script won't install the correct version.

Go here:
https://nodejs.org/en/download/current/

Find the binary "ARM Binaries (.tar.xz): ARMv6".

Run the commands like this:

```
mkdir ~/Downloads/nodejs
cd ~/Downloads/nodejs
wget https://nodejs.org/dist/v6.3.0/node-v6.3.0-linux-armv6l.tar.xz
tar -xvf node-v6.3.0-linux-armv6l.tar.xz
sudo cp -r node-v6.3.0-linux-armv6l/* /usr/local/

sudo npm install npm -g
```
