### ISSUE TITLE
Button Input Help

### ISSUE THREAD

**Issue by Eddie-Hartman** [amzn/alexa-avs-raspberry-pi#109]
I have the java code written with the correct things imported so that hopefully I could activate Alexa with a button press. The code that I'm using is [this](http://pi4j.com/example/listener.html) and I added it into  AVSApp.java. My code compiles and runs, but I get this
`SEVERE: Unable to load [libpi4j.so] using path: [/lib/libpi4j.so] java.io.FileNotFoundException: File /lib/libpi4j.so was not found in classpath. 	at com.pi4j.util.NativeLibraryLoader.loadLibraryFromClasspath(NativeLibraryLoader.java:138)`
 error when running it. I do not know enough about Maven or classpaths and was hoping someone could help me. Thanks.

**Comment by lemire** [comment]
What happens if you type "locate libpi4j.so"?

**Comment by Eddie-Hartman** [comment]
@lemire Nothing

**Comment by lemire** [comment]
The code you are using relies on pi4j. Did you try installing pi4j?

It is not part of the Java VM.

**Comment by Eddie-Hartman** [comment]
@lemire pi4j is installed and I ran a test program to make sure my wiring is correct. It does not work with the maven art of the project because something is wrong with the maven configurations and I don't know how to fix them.

**Comment by Eddie-Hartman** [comment]
I got it working and will update [this](https://github.com/Eddie-Hartman/alexa-avs-raspberry-pi-button) with steps to get everything working.
