### ISSUE TITLE
error npm start

### ISSUE THREAD

**Issue by scova0** [amzn/alexa-avs-raspberry-pi#112]
Hye

I have a problem when I launch npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Alexa/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'Alexa/samples/javaclient/certs/server/node.key'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/home/pi/Alexa/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start" "-loglevel" "info"
npm ERR! cwd /home/pi/Alexa/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Alexa/samples/companionService/npm-debug.log
npm ERR! not ok code 0

Thank you for your help.

**Comment by keleric** [comment]
You provided an incorrect relative path. Either use an absolute path, or '../javaclient/certs/server/node.key'

**Comment by scova0** [comment]
Thx a lot


It's much better

Bad: Alexa/samples/javaclient/certs/server/node.key

Ok: /home/pi/Alexa/samples/javaclient/certs/server/node.key
