### ISSUE TITLE
mvn validate

### ISSUE THREAD

**Issue by scova0** [amzn/alexa-avs-raspberry-pi#119]
Hye Everyone

When I execute mvn validate my rpy return bash: mvn: command not found
the same for mvn install.

mpn in launch

Thx for your help

**Comment by scova0** [comment]
It's ok

I had a problem in step 2.7


I restarted step 2.7 and that's good

**Comment by kmanan** [comment]
Hi, I'm facing the same issue. Not sure what you mean by step 2.7. Any help?

**Comment by saurav2107** [comment]
hi All,

I ran into a similar issue, I can run mvn when I connect my rPi with SSH [as I install maven from SSH], but as specified in Step:9 to start client while on VNC connection, bash gave me the error of command not found. Please help me out as it seems I am very close to completion of ALEXA setup.

PS: I am very new to Linux ecosystem.
Thanks in advance

**Comment by mayuresh23sawant** [comment]
Even I am facing the same issue with no solution. Did you find any solution to it?
