### ISSUE TITLE
Amazon music is not supported on this device.

### ISSUE THREAD

**Issue by ARastogi19** [amzn/alexa-avs-raspberry-pi#12]
I've **"Enable Amazon Music? *"** set to **"Yes"** but I still get **"Amazon music is not supported on this device."** error. How do I get it working?

**Comment by stayupthetree** [comment]
I wondered this as well, but noticed on the Music page when setting up the Security Profile, it says "Approval Status:  PENDING"

My assumption is that once they approve Music, the music portion will work.

**Comment by vwillcox** [comment]
I hope so. Would keep me paying for my Amazon Prime account for the third year if they let me use this feature!

**Comment by bill-orange** [comment]
After almost three weeks, Amazon approved my 'MUSIC' request.  Almost like magic, I can can now stream the music already stored in Amazon Cloud.  I am not a prime member.

There IS Hope.

Bill

**Comment by elstryan** [comment]
Yes stayupthetree is correct - after requesting Amazon music you must have to wait for your request to be approved. Glad that it was approved for bill.

**Comment by cfaulk** [comment]
Mine has been pending for 2 months now. I emailed amazon twice and this is the latest response.....

Hi Corey, thank you for your inquiry. Currently all Amazon Music approvals are in a pending state. Unfortunately, there is no further information I can share with you at this time. We appreciate your patience with this issue while we work towards a resolution.  I apologize for the inconvenience.

Kim C.
Alexa Skills Team

**Comment by interbiznw** [comment]
Cfaulk, just got that same response.

**Comment by howardguo** [comment]
where to find "Enable Amazon Music? "??

**Comment by clark173** [comment]
@howardguo did you ever find out where you can enable it? I am running into the same issue.

**Comment by howardguo** [comment]
@clark173 this is the email I got bellow:
“Hi howardguo, we apologize for the lack of clarity on Amazon Music approvals. Amazon Music is currently limited to Alexa-enabled devices that are approved for commercial distribution and use. If you are developing a commercial device, please let us know. We’d love to help. Thanks for being an AVS developer.

**Comment by cfaulk** [comment]
Nice. I would tell them you are developing a commercial device and see what
they ask.
