### ISSUE TITLE
Line with format PCM_SIGNED, ..., little-endian not supported

### ISSUE THREAD

**Issue by anhcuong** [amzn/alexa-avs-raspberry-pi#121]
![2016-04-12 18_04_35-alexabug](https://cloud.githubusercontent.com/assets/7950613/14456782/3fae6342-00d9-11e6-848d-3f4ffae1712d.png)

**Comment by ajotwani** [comment]
@anhcuong Have you see these threads for PCM_SIGNED errors? https://github.com/amzn/alexa-avs-raspberry-pi/issues?utf8=%E2%9C%93&q=label%3APCM_SIGNED+

**Comment by ajotwani** [comment]
Closing as Duplicate.
