### ISSUE TITLE
iOS Swift App?

### ISSUE THREAD

**Issue by rplankenhorn** [amzn/alexa-avs-raspberry-pi#122]
Can you convert the iOS sample app to Swift?  I don't think anyone is going to realistically want to start a new app in Objective-C these days and it would be good to have some sample code in Swift.

**Comment by ajotwani** [comment]
We do not have any sample code in Swift. However, it is possible that some other community members do. This might help https://forums.developer.amazon.com/forums/thread.jspa?messageID=23084&#x5A2C;
