### ISSUE TITLE
npm can't find package.json file

### ISSUE THREAD

**Issue by fskemery** [amzn/alexa-avs-raspberry-pi#123]
I'm a nooby here and up until step 8 everything seemed to be working for me on this Raspberry pi AVS project.  When I enter the npm start command, I get the following on screen in terminal. Bug log file follows below. 

Looks like it can't find the package.json file which is currently sitting in /opt/alexa-avs/samples/companionService/package.json.  If that's true I'm not clear from the Bug log where I should move this file to?

 Any help would be greatly appreciated.

Thanks in advance

Frank
> alexa-voice-service-sample-companion-service@1.0.0 start /opt/alexa-avs/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

SyntaxError: Invalid flags supplied to RegExp constructor 'alexa'
    at new RegExp (<anonymous>)
    at Object.<anonymous> (/opt/alexa-avs/samples/companionService/config.js:33:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/alexa-avs/samples/companionService/authentication.js:4:14)
    at Module._compile (module.js:456:26)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/alexa-avs/samples/companionService/npm-debug.log
pi@raspberrypi:/opt/alexa-avs/samples/companionService $ 

Debug log.

[npm-debug.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/215577/npm-debug.txt)

**Comment by dpeach** [comment]
This looks like the problem I was having (though I didn't research it fully). My problem was that I didn't have anything on my computer that was node (by itself), only nodejs. The nodejs was at /usr/bin/nodejs. I made a symlink by typing:
`sudo ln -s /usr/bin/nodejs /usr/bin/node`
That has gotten me past this step. I am still in the process of getting up and running, but thought I would jump in with an answer.

**Comment by fskemery** [comment]
Thanks but that does not appear to be my problem. node already exists on my system in the bin directory. 

Frank 

----- Original Message -----

**Comment by keleric** [comment]
It looks like it might be something to do with your config file. Can you paste it here? (omit your client secret)

**Comment by fskemery** [comment]
Thanks for reaching out to me and offering to help. Much appreciated. 

Here's my configfile 

/** 
* @module 
* This module defines the settings that need to be configured for a new 
* environment. 
* The clientId and clientSecret are provided when you create 
* a new security profile in Login with Amazon. 
* 
* You will also need to specify 
* the redirect url under allowed settings as the return url that LWA 
* will call back to with the authorization code. The authresponse endpoint 
* is setup in app.js, and should not be changed. 
* 
* lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should 
* not need to modify those elements. 
*/ 
var config = { 
clientId: 'amzn1.application-oa2-client.XXXXXXXXXXXXXXXXXXXXXX58', 
clientSecret: '1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXc', 
redirectUrl: 'https://localhost:3000/authresponse', 
lwaRedirectHost: 'amazon.com', 
lwaApiHost: 'api.amazon.com', 
validateCertChain: true, 
sslKey: '/home/pi/optalexa-avs/samples/javaclient/certs/server/node.key', 
sslCert: '/home/pi/opt/alexa-avs/samples/javaclient/certs/server/node.crt', 
sslCaCert: '/home/pi/opt/alexa-avs/samples/javaclient/certs/ca/ca.crt', 
products: { 
"my_device": ["581953"], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"] 
}, 
}; 

module.exports = config; 

/opt/alexa-avs/samples/javaclient/config.json 

Thanks Again 

Frank 
----- Original Message -----

**Comment by keleric** [comment]
It seems as though you have too many commas. Remove the comma at the end of ["581953"], and at the end of the products object.

**Comment by fskemery** [comment]
Thanks. 

Not sure where in the file your reference to " end of the products object." meant? I this what you were referencing? ["DSN1234", "DSN5678"] 
}, 

----- Original Message -----

**Comment by keleric** [comment]
products: {
"my_device": ["581953"], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
},

Should be 

products: {
"my_device": ["581953"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
}

**Comment by fskemery** [comment]
Thanks I will try that much appreciated. 

Frank 

----- Original Message -----

**Comment by Bacchusm** [comment]
Hi, I believe I am having the same problem.  I tried removing the extra comma on the config file.   That didn't work.   Here is the npm-debug.log and the config file.   

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/bin/node
5 verbose stack Error: ENOENT, open '/home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json'
6 verbose cwd /home/pi/Downloads/alexa-avs-raspberry-pi-master
7 error Linux 4.1.19-v7+
8 error argv "/usr/bin/node" "/usr/bin/npm" "start"
9 error node v0.10.44
10 error npm  v2.15.0
11 error path /home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json
12 error code ENOENT
13 error errno 34
14 error enoent ENOENT, open '/home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ 34, true ]

Config file/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.f5d52fxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxfx9x4x2xaxxxxx',
    clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx750347d55bb5033ce702xxxxxxxxxxx',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.key',
    sslCert:'/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.crt', 
    sslCaCert: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/ca/ca.crt',
    products: {
        "my_device": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;


Thank you for your help in advance.

Mike

**Comment by Bacchusm** [comment]
Hi Keleric,

I believe I am having the same problem.  

There is no package.json in the main directory there 
Here is the error log:


0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/bin/node
5 verbose stack Error: ENOENT, open '/home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json'
6 verbose cwd /home/pi/Downloads/alexa-avs-raspberry-pi-master
7 error Linux 4.1.19-v7+
8 error argv "/usr/bin/node" "/usr/bin/npm" "start"
9 error node v0.10.44
10 error npm  v2.15.0
11 error path /home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json
12 error code ENOENT
13 error errno 34
14 error enoent ENOENT, open '/home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ 34, true ]


Here is the config file
/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.f5x2xxcx7x4xc2xxxxxxxxxxxxxxxxxxx',
    clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxzzzyyyyyyyyyyyyyyyyyyyy33yyxxxxxxxxxxxxf',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.key',
    sslCert:'/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.crt', 
    sslCaCert: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/ca/ca.crt',
    products: {
        "my_device": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;

**Comment by Bacchusm** [comment]
Hi Keleric,

I believe I am having the same problem.

There is no package.json in the main directory there 
Here is the error log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/bin/node
5 verbose stack Error: ENOENT, open '/home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json'
6 verbose cwd /home/pi/Downloads/alexa-avs-raspberry-pi-master
7 error Linux 4.1.19-v7+
8 error argv "/usr/bin/node" "/usr/bin/npm" "start"
9 error node v0.10.44
10 error npm v2.15.0
11 error path /home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json
12 error code ENOENT
13 error errno 34
14 error enoent ENOENT, open '/home/pi/Downloads/alexa-avs-raspberry-pi-master/package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ 34, true ]

Thank you in advcance

**Comment by Bacchusm** [comment]
Sorry here is the config file.

/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.f5xxxxxxxxxxxxxxxx',
    clientSecret: 'xxxxxxxxxxxxxe5e01ex33cxxxxxxxxxxxxxxxxxx',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.key',
    sslCert:'/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.crt', 
    sslCaCert: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/ca/ca.crt',
    products: {
        "my_device": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;

**Comment by Bacchusm** [comment]
/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.f5xxxxxxxxxxxxxxxx',
    clientSecret: 'xxxxxxxxxxxxxe5e01ex33cxxxxxxxxxxxxxxxxxx',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.key',
    sslCert:'/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.crt', 
    sslCaCert: '/home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/certs/ca/ca.crt',
    products: {
        "my_device": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;

**Comment by keleric** [comment]
products: {
        "my_device": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },

has an extra comma on the end. Should be this:

    products: {
        "my_device": ["123456"] // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    }

**Comment by Bacchusm** [comment]
Sorry, for being so blind.  I'll check that when I get home.  Thank You!

**Comment by Bacchusm** [comment]
I took the comma out and that didn't help.  

What helped ( me at least ) was rereading the instructions and changing the directory to:
cd <REFERENCE_IMPLEMENTATION>/samples/companionService

Thank you

Bacchusm

**Comment by Bacchusm** [comment]
All working... 
Thank You

**Comment by ajotwani** [comment]
Closing as resolved.
