### ISSUE TITLE
maven project redirect issue 

### ISSUE THREAD

**Issue by wah2957** [amzn/alexa-avs-raspberry-pi#124]
I know the build isn't finding  the POM  correctly. The website for maven help stated the following : 

"mvn -f path/to/pom.xml <goals> ..."  I'm confused on  what i need to input in am i putting the path where it says "path/to/pom.xml" or is that actually in the command. im not a programer and need help please ! 

INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.462 s
[INFO] Finished at: 2016-04-12T17:30:29+00:00
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (default-cli): Goal requires a project to execute but there is no POM in this directory (/root). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by keleric** [comment]
You should be running mvn install && mvn exec:exec from within the javaclient sample directory. It seems as though you're trying to run it from /root...

**Comment by ajotwani** [comment]
@wah2957 can you please confirm if @keleric's response resolved your issue?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
