### ISSUE TITLE
can't auto start alexa

### ISSUE THREAD

**Issue by jkepple2003** [amzn/alexa-avs-raspberry-pi#127]
I can't get the autostart file I made called alexaVoice to work correctly. I can get Alexa to work but I have to go to the terminal and type cd Downloads/alexa-avs-raspberry-pi=master/samples/javaclient/ and then use the mvn exec:exec command. I'm guessing the autostart file doesn't work because I left all the files in the Downloads directory but is there a way I can edit the file so it will start in the right directory?

**Comment by IrishClanger** [comment]
@jkepple2003 What have you put in the autostart file? You need to add lines to run batch files to start the various parts like this:
@lxterminal --command "/home/pi/alexa1"
@lxterminal --command "/home/pi/alexa2"
@lxterminal --command "/home/pi/alexa3"

Then my alexa1 file (which is executable) contains:

cd /home/pi/avs/alexa-avs-raspberry-pi-master/samples/companionService
npm start 
sleep 86400

My alexa2 file contains:

cd /home/pi/avs/alexa-avs-raspberry-pi-master/samples/javaclient
mvn exec:exec
sleep 86400

and my alexa3 file contains the xdotool commands.

**Comment by smiley4017** [comment]
You can make this into 1 script by putting & after npm start
ie: 
cd /home/pi/avs/alexa-avs-raspberry-pi-master/samples/companionService
npm start &
cd /home/pi/avs/alexa-avs-raspberry-pi-master/samples/javaclient
mvn exec:exec

What is xdotool commands?

**Comment by Ikol18** [comment]
Guys please help
Everything is setup perfectly with oracle java 8, maven ,node and everything
When I click on start listening the bar indicates its listening but when I press stop its not giving output
please help me
useful info:
using rpi2
usb sound card with mic input and speaker output(both are in working condition)
node v 5.10.0 and npm v3.8.3

**Comment by picmax** [comment]
Check this: #156

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by Rian9771** [comment]
Is it normal that everytime i start the client, it pops up Login to Register/Authenticate your device and then tries to open web browser to get the Token?

cd ~/Desktop/alexa-avs-sample-app/samples && cd javaclient && mvn exec:exec

I was hoping to run all three commands so i can run Alexa AVS automatically without any input.

**Comment by realn0whereman** [comment]
Rian9771 - yes, unfortunately it is. I have my personal beliefs for why Amazon devs did this, but this is not good enough for me. I am hacking into this to try and automate this part away with phantomjs. I'd like to have a production quality alexa app which auto starts as soon as the raspberry pi boots up, with no further user input. Will update if I have something working.

**Comment by realn0whereman** [comment]
Ha! I got it to work. Let me clean up the code and I'll post a diff.

**Comment by Rian9771** [comment]
Excellent work @realn0whereman . Will wait to see your updates! Thanks

**Comment by anh1e** [comment]
@realn0whereman... Wow that's a good news for a lot of folks including me ;) pls share your work.

**Comment by realn0whereman** [comment]
Okay, here's part 1: changes made to companionService

I have phantomJS 2.1.1. installed on my rasbperry pi 3 ( It was pretty easy, I found someone who already did it online and reused their efforts. Maybe installable from regular repos? Maybe there's arm binaries available? I honestly don't remember), and am running raspian jessie

http://pastebin.com/65uHpwMb

This is a dangerous diff. PLEASE DO NOT COMMIT THIS DIFF ANYWHERE ONLINE. Reason being, this is a naive for-home-use kind of code. If you commit publicly, your credentials may leak. I was too lazy to properly package this for consumption or integrate it with KMS or something actually secure. 

So what's going on here:

When you go to localhost:3000/abc-123-345, you pass a registration code to the nodeJS server. It uses this to create an authUrl, and redirects you to it. The magic above does the work your browser would do. It uses phantomJS to open the page, insert your credentials, hit submit, and wait for the redirect back to the raspberry pi (which contains the access token). Please let me know if you have any questions. 

Stay tuned for Part 2 where I share what I did with the java code to achieve 0-click bootup for alexa raspberry pi.

-Realn0whereman

**Comment by nsouto** [comment]
This is great, thanks for the info @realn0whereman, looking forward for Part 2.

**Comment by realn0whereman** [comment]
Okay Part 2:

Java changes:
http://pastebin.com/dYY8Qmxd

I deleted the part that pops up the YES NO popup box with the url for you to click through.

Now, when the provisioning thread starts in the java client, it gets the url it would display to you, and automatically invokes a call to it. Then it loops and waits for the nodeJS to do it's phantomJS magic and authorize your device.

**Comment by nsouto** [comment]
@realn0whereman thanks for the code, after looking through it, it makes perfect sense what you did. I'm however having some issues after getting it all setup I'm getting an exception "Missing Session Id Parameter" thrown on line 34 of samples/javaclient/src/main/java/com/amazon/alexa/avs/auth/companionservice/CompanionRegCodeResponse.java

```20:59:09.573 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
java.lang.IllegalArgumentException: Missing sessionId parameter
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceRegCodeResponse.<init>(CompanionServiceRegCodeResponse.java:34) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:162) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:100) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:94) [classes/:?]
```

**Comment by realn0whereman** [comment]
Does the nodeJS window show any output?

**Comment by nsouto** [comment]
@realn0whereman yes here is what it's showing, looks normal to me:

`> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
`

**Comment by realn0whereman** [comment]
Yeah, this is a two part install - your nodeJS window should show output about phantomJS. Did you install that?

**Comment by nsouto** [comment]
@realn0whereman yeah I installed phantomJS, when I run it I get a phantomJS> prompt, not sure if there is anything else I need to do.

**Comment by nsouto** [comment]
@realn0whereman Must be something with the Java, either I patched it wrong or something else, when I try the un-patched Java (even with the phantomJS changes on the node) I get the prompt to open the browser with the proper URL so it seems it's something related to that first request, I just haven't been able to figure out how to debug it yet...

**Comment by realn0whereman** [comment]
This is what my nodeJS output looks like:
http://pastebin.com/f1ZMri5j


I see where the exception is coming from but nothing is occurring to me yet. I'm thinking....

The flow is like this:

NodeJS starts up
Java client starts up
remoteProvisiongThread starts up and make a call to https://localhost:3000/provision/regCode (note: in order to curl this, you have to setup the client cert, key, and GET parameters)
nodeJS gets call, and returns a registration code and sessionID (In your case, the sessionID does not come back (insert a print statement in the nodeJS to see if it gets the call?))
java gets sessionID and regCode, and calls https://localhost:3000/provision/123-abc-def-xyz (the regCode)
nodeJS gets the call, and then calls out to phantomJS to do all the magic.

Does your javaclient/logs/application.log show anything?
I would add print statements to the getRegistrationCode method to see what's called and with what parameters, and what's specifically returned (what is in that JSONObject)

The additional output I posted is printed after the regCode is acquired (where the problem you posted about currently resides), and the provision/123-abc-def-xyz url is called.

**Comment by nsouto** [comment]
@realn0whereman So yeah, it was something with my system, took some time to get everything re-installed I get the PhantomJS output as you do.

The only issue now that I'm trying to get around is that the Token doesn't update.

If you have any tips on how to debug that it would be great, I'll keep at it and report once I get it working.

**Comment by nsouto** [comment]
@realn0whereman Found the issue... I was using phantomJS 1.9.8, I tried with version 2.1.1 and it works well now

Thank you so much for the work you did to get this automatic

**Comment by pavanagrawal123** [comment]
@nsouto @realn0whereman : which method are you all using to start up the alexa on boot? I've got the login feature working, (with pull request #431 ), but have not been able to start it up on boot. Any insight? Thanks.

**Comment by pavanagrawal123** [comment]
ended up using the ~/.config/autostart/ with a bash script with #431 , works perfect!

**Comment by charliegilliland** [comment]
@pavanagrawal123 I'm glad to hear you found my #431 useful! I've just read through this thread, and I thought I'd share my thoughts on the subject of auto-start. I am using an Odroid-XU4, which is another ARM mini pc like the Raspberry Pi. It runs Ubuntu 16, so I simply added two startup scripts to start the clientService and javaclient apps at boot. 
For the auto-login function, I added another class (AutlLogin.java) that uses Selenium to interact with the login page. Selenium is a maven dependency, so I just added it to the pom.xml. I went ahead and added my functionality to all the necessary files, such as config.json, pom.xml, AVSApp.java, DeviceConfig.java, and DeviceConfigUtils.java, in the hope that this could be merged soon as a new feature. I think this approach is as simple as it gets since there are no extra programs to set up: just put your amazon username and password into the config.json file, set autoLoginEnabled=true, and you're good to go!
This is my first time to contribute to a GitHub project, and it's really encouraging to see people are finding it useful! Thanks!

**Comment by lslamp** [comment]
I followed the instructions and it did not work for me. I think I have done something wrong. Or did not understand the driver

Lawrence

**Comment by charliegilliland** [comment]
@lslamp Please see my response here: #431

**Comment by anh1e** [comment]
@pavanagrawal123 can you share your bash script ? ..."using the ~/.config/autostart/ with a bash script"

**Comment by anh1e** [comment]
not sure it's the best way but I ended up using these commands in bash script and it works....

lxterminal -l -e 'cd ~/Downloads/alexa-avs-sample-app/samples/companionService && npm start ; /bin/sh'
sleep 10s
lxterminal -l -e 'cd ~/Downloads/alexa-avs-sample-app/samples/javaclient && mvn exec:exec ; /bin/sh'
sleep 1m
lxterminal -l -e 'cd ~/Downloads/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e kitt_ai ; /bin/sh'

**Comment by Misfitsman805** [comment]
@realn0whereman Quick question, how do I apply your diff patches and what files do they get applied to? Thanks.

**Comment by xeonqq** [comment]
@realn0whereman your patch works. I manually copy the changes into the files, because of the update in the master.
Maybe some additional comments:
I installed the phantomjs from https://github.com/fg2it/phantomjs-on-raspberry
And after modifying the java files, you have to recompile them, by running ```mvn validate && mvn install``` under the folder ```alexa-avs-sample-app/samples/javaclient```

**Comment by alemehaute** [comment]
@Misfitsman805 @realn0whereman I have the same question and I'd appreciate it if you could clear it up for me, as well as how to run the script for the autostart.
Thanks in advance.

**Comment by frakman1** [comment]
While I appreciate the hard work everyone has put into this (especially @realn0whereman ), don't understand why this functionality isn't rolled into the mainline code in git. The install scripts can use the user-unique credentials and import them into the appropriate code and take care of the automation.

**Comment by frakman1** [comment]
@realn0whereman
I manually added your patches, recompiled them, and am using phantomjs version 2.1.1 and ran into this error when running the javaclient:
```
pi@raspberrypi:~ $ cd ~/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:203)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1590)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:220)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2701)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2623)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1806)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:203)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callProvisioningWithRegCode(CompanionServiceClient.java:273)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:73)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:60)
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1572)
	... 20 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 26 more
```

I tried adding the aws.amazon.com certificate using the keytool utility but that didn't change anything. I even made sure that I ran `apt-get install -certificates`.

Does anyone know how to  get around this particular error?
