### ISSUE TITLE
mvn validate

### ISSUE THREAD

**Issue by tdseward** [amzn/alexa-avs-raspberry-pi#129]
I have alexa listening but when I tried to build the app I can not get mvn validate to recognize maven, using mvn validate

I get

bash: mvn: command not found

I double checked the location /opt/apache-maven-3.3.9 and it is there. I double checked the maven.sh in the ect/profile.d/  In fact I  rebuilt it of course I logged out and then backin... still nothing.  

So Now when I am trying to reinstall after downloading again from the root apache-maven using sudo tar zxvf /home/pi/Downloads/apache-maven-3.3.9-bin.tar.gz -C /opt OR even within the Downloads directory 

I am getting... (child): /home/pi/Downloads/apache-maven-3.3.9-bin.tar.gz Cannot open: No such file or directory tar (child): error is not recoverable: exiting now tar: Child returned status 2 tar: Error is not recoverable: exiting now

Any ideas on the two issues?

**Comment by AmarajulaPrathyusha** [comment]
sudo tar -xvzf apache-maven-3.3.9-bin.tar.gz
