### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by jaysonmsaavedra** [amzn/alexa-avs-raspberry-pi#13]
Hi, made it to the step where you run mvn install. I earlier had trouble getting my pi user to work with maven. Root would, but I don't know if I setup the maven.sh correctly. So I'm trying to run mvn install and i get build failure. I'm pretty new to stuff like this, and any suggestions would be awesome. If you have questions for me that'd help you understand my problem i'd get back to you asap. thanks

**Comment by jaysonmsaavedra** [comment]
I get 
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[ERROR] Failed to execute goal org.apache.maven.plugins-resources-plugins:2.6:resources (default-resources) on project sample-java-client: Cannot creat resource output directory: /home/pi/Downloads/samples/javaclient/target/classes -> [Help 1]

**Comment by jaysonmsaavedra** [comment]
And also for some reason it says "Building Alexa Voice Service Sample Java Client 20160207.0"
I don't know why it's such a large number or if it's supposed to be such a large number.

**Comment by sleepingscorpion** [comment]
This looks like it's environment related, and not an issue with this software release. Re.the 'large number'  it's the release date in format yyyymmdd

Plenty if maven specific resources out the to get you going.

**Comment by jaysonmsaavedra** [comment]
Hey guys, anyone else who comes across this problem I managed to successfully build it. I had to make the build platform independent with 
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
between the <property> tags. and I also was getting an error saying i couldn't execute the goal, and to fix this I just went to the root user
sudo -i
and ran mvn install and got success. Hope this helps anyone!
Oh,  also I had jdk 1.8.0_77 and it isn't compatible, so you have to install 1.8.0_73 from the oracle archives and switch to that with
sudo update-alternatives --config java
Hope this helps!

**Comment by vlasov01** [comment]
It seems that step 9 missing VLC_PATH variable definition. I've added export VLC_PATH=/usr/lib/vlc .
As well Instead of running 
`mvn validate`
I'm running
`mvn validate compile`

**Comment by stayupthetree** [comment]
"Building Alexa Voice Service Sample Java Client 20160207.0" 

That large number is a date.

**Comment by jaysonmsaavedra** [comment]
Right, I asked this question after working on this for like 6 hours straight at 5am in the morning, kinda dumb I didn't notice

**Comment by KevinHanson** [comment]
I am getting a build failure at the step mvn exec:exec. I get the error "failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default cli) on project sample-java-client: Command execution failed" I originally installed jdk 1.8.0_77 and as jasonmsaavedra suggested in went to version 1.8.0_73 with no change in build results. Any suggestions on a path to get a successful build?

**Comment by vlasov01** [comment]
@KevinHanson 
Try to run with some debug information output:
`mvn -e -X exec:exec`
It may help understand the issue.

**Comment by KevinHanson** [comment]
@vlasov01 Found it! It was hard to see the error which was "sslCleitnKeyStore is blank in you config file" which lead me to the config.json file, which lead me to provide the client.pkcs12 file location and passphrase, which lead to a successful MVN execution. Thank you for your help!

**Comment by vlasov01** [comment]
@KevinHanson Glad it helped you!
