### ISSUE TITLE
Unknown error. Is this because I don't have an usb mic?

### ISSUE THREAD

**Issue by tromso** [amzn/alexa-avs-raspberry-pi#130]
Shouldn't I get at least a tone from Alexa?
http://raspberrypi.stackexchange.com/questions/45900/failed-to-set-up-alexa-on-rpi3-i-get-just-one-final-error-at-the-end-despite-bu

**Comment by ajotwani** [comment]
Do you get "An error occured creating speech request" error in the console?

**Comment by tromso** [comment]
That was solved when I plugged an USB microphone.
