### ISSUE TITLE
java client getting java.util.concurrent.TImeoutException

### ISSUE THREAD

**Issue by chalda** [amzn/alexa-avs-raspberry-pi#134]
[RequestThgread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException

**Comment by ajotwani** [comment]
It's probably related to your microphone. Please see these https://github.com/amzn/alexa-avs-raspberry-pi/labels/sound%2Fmicrophone, and post on one of these open issues. Closing this as duplicate.

**Comment by chalda** [comment]
The pick up from the mic is working. The bar indicator responds when I talk
into it. I also hear beeps from my TV when I click listen so I don't think
that's the problem tbh
