### ISSUE TITLE
NPM Install in ../samples/companionService continuously fails -- multiple reinstalls no help

### ISSUE THREAD

**Issue by neil111** [amzn/alexa-avs-raspberry-pi#136]
Hi everyone. I'm installing this project on an RPi v2b.  I've followed all steps carefully (famous last words :-).  At Step #5 I always get these errors. The log is below. Note that I've tried every recommendation I could find, including uninstalling, updating, upgrading, and loading a new verison of node.

I would truly appreciate any suggestions, because I'm out of ideas (and googling for them too).
Regards,
Neil

pi@raspberrypi ~/AlexaTest/samples/companionService $ npm install
npm http GET http://registry.npmjs.org/body-parser
npm http GET http://registry.npmjs.org/debug
npm http GET http://registry.npmjs.org/node-uuid/1.4.1
npm http GET http://registry.npmjs.org/express
npm http 304 http://registry.npmjs.org/body-parser

npm ERR! Error: No compatible version found: body-parser@'>=1.12.4- <1.13.0-'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/AlexaTest/samples/companionService/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/AlexaTest/samples/companionService
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: body-parser@'>=1.12.4- <1.13.0-'
npm ERR! message Valid install targets:
npm ERR! message ["1.0.0","1.0.1","1.0.2"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/AlexaTest/samples/companionService/npm-debug.log
npm not ok
pi@raspberrypi ~/AlexaTest/samples/companionService $

**Comment by neil111** [comment]
Also, please note that my node.js version is v0.6.19

**Comment by ajotwani** [comment]
I'd recommend following the steps for Node install, so run the following on the terminal -

sudo apt-get update 
sudo apt-get upgrade
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install nodejs

Let us know if that fixes it. Thanks!

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by vaibhavbhanawat01** [comment]
![img_20170725_102928](https://user-images.githubusercontent.com/12860795/28556499-6733f870-7124-11e7-9f1b-df75e1dacb21.jpg)

Hi, i am getting this while running the companion services
