### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by ncreegan** [amzn/alexa-avs-raspberry-pi#137]
Hi guys.

I'm hitting an error on part 8 (npm start). I've since gone back and reviewed all my work on parts 4-7, assuming there was a typing error, but found nothing.

`pi@raspberrypi:~/alexa-avs-raspberry-pi-master/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/home/pi/alexa-avs-raspberry-pi-master/samples/companionService/config.js:17
    clientId: amzn1.application-oa2-client.***************************************,
                                          ^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/alexa-avs-raspberry-pi-master/samples/companionService/authentication.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log`

**Comment by keleric** [comment]
client id needs to be a string:

clientId: "amzn.****",

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
