### ISSUE TITLE
mvn install build failure

### ISSUE THREAD

**Issue by crlanglois** [amzn/alexa-avs-raspberry-pi#139]
Thanks in advance for any tips:

mvn validate succeeds, mvn install fails
I'm running from the javaclient directory
Java version 1.8.0_77 is installed

pi@raspberrypi:~/alexa-avs-raspberry-pi-master/samples/javaclient $ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.java.dev.jna:jetty-util:jar:9.3.7.v20160115 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.986 s
[INFO] Finished at: 2016-04-18T14:35:30+00:00
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sample-java-client: Could not resolve dependencies for project com.amazon.alexa.avs:sample-java-client:jar:20160207.0: Failure to find net.java.dev.jna:jetty-util:jar:9.3.7.v20160115 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ajotwani** [comment]
See this FAQ for "Companion Service" errors. See https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors. Scroll all the way down.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
