### ISSUE TITLE
can this be run headless Help Please

### ISSUE THREAD

**Issue by LEDTECHCHGO** [amzn/alexa-avs-raspberry-pi#143]
i got close to the end of the set up and when i ran the mvn exec:exec
 im getting: iknow there is looking for graphical display 

Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)

specs:
pi 2+
jessie lite 

so my question is can this be ran this be run headless and what options would i have to set to get pass loking for a grapical display on istalll any help please

**Comment by sjfischr** [comment]
It can be run headless, but you have to log in using VNC in order to get the graphics working. The best way to do this is by downloading the [VNC Viewer for Chrome](https://chrome.google.com/webstore/detail/vnc%C2%AE-viewer-for-google-ch/iabmpiboiopbgfabjmgeedhcmjenhbla?hl=en).

**Comment by LEDTECHCHGO** [comment]
so you have to  install the vnc server on pi first right

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by acidhax** [comment]
It's an issue and running a VNC server is not headless. Is it possible to run this headless without X11. I'm doing this over ssh.

**Comment by prijswij** [comment]
Same here. 
From my ubuntu machine is just do 'ssh -X pi@rpi.ip.address'

**Comment by DaAwesomeP** [comment]
I do not wish to install X, a display manager, or VNC on my system. I was able to install VLC headless and OpenJDK headless, but it doesn't work:
```log
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
        at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.602 s
[INFO] Finished at: 2016-12-16T15:26:42-06:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
If the X is needed to initiate an OAuth response, this can either a) be done with a terminal prompt, or b) use access tokens.

**Comment by acidhax** [comment]
@ajot Are you dead?

**Comment by architek1** [comment]
Still nothing? I'm having the same issue.
