### ISSUE TITLE
Listening starts and then stops

### ISSUE THREAD

**Issue by mkarliner** [amzn/alexa-avs-raspberry-pi#144]
I've gone through all the steps and got to a dialog with a 'Start Listening' button.
I have a bearer token showing. If I click on Start Listening, I hear a ding and then
the button reverts to Start Listening a second or two later.

I have gone through all steps successfully except 10.3 Device Authorisation. I did not 
get redirected on login, but was immediately shown a screen that said device tokens ready.

Any ideas?

**Comment by keleric** [comment]
The reference client automatically ends listening if it can't hear you. Try speaking *very* close to your microphone

**Comment by ajotwani** [comment]
@mkarliner can you confirm if you are still having an issue?

**Comment by mkarliner** [comment]
This one can be closed. I've open #147 now.
