### ISSUE TITLE
NPM Start Failure  

### ISSUE THREAD

**Issue by fskemery** [amzn/alexa-avs-raspberry-pi#146]
When I attempt to run the client in step 8 I get the following error messages on screen.  Debug file contents follow.  Can anyone tell me what I may need to do to correct this?

thanks in advance for any assistance you may be able to provide.

And yes I am a Nooby.
Frank

Error  message

i@raspberrypi:/opt/alexa-avs/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /opt/alexa-avs/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/opt/alexa-avs/samples/companionService/config.js:33
/opt/alexa-avs/samples/javaclient/config.json
^

SyntaxError: Invalid flags supplied to RegExp constructor 'alexa'
    at new RegExp (native)
    at Object.<anonymous> (/opt/alexa-avs/samples/companionService/config.js:33:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/opt/alexa-avs/samples/companionService/authentication.js:4:14)
    at Module._compile (module.js:435:26)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/alexa-avs/samples/companionService/npm-debug.log

NPM Debug log contents

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
11 verbose cwd /opt/alexa-avs/samples/companionService
12 error Linux 4.1.19-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls alexa-voice-service-sample-companion-service
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ajotwani** [comment]
Can you check your config.json and config.js files to make sure they don't have any typos, and the device id matches? See this FAQ https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors. Scroll all the way down.

**Comment by fskemery** [comment]
Thanks for responding.  I have rebuilt the projet from scratch and triple checked teh config.json, config.js and ssl.conf files.  See attached.  any other thoughts on why this is not working for me? 

[configjs..txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/233458/configjs.txt)
[configjson.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/233459/configjson.txt)
[sslcnf.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/233460/sslcnf.txt)

[npm-debuglog.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/233462/npm-debuglog.txt)

Thanks

**Comment by fskemery** [comment]
Sorry I accidentally closed this earllier I'm still dealing with this issue

Any thoughts anyone?

**Comment by erikhopf-amzn** [comment]
No problem. Can you confirm that you are using the full path to your certs? See the instructions below:

Step 6: Edit the configuration file for the Node.js server

The configuration file is located at:

<REFERENCE_IMPLEMENTATION>/samples/companionService/config.js. 

Make the following changes:

    Set sslKey to <REFERENCE_IMPLEMENTATION>/samples/javaclient/certs/server/node.key
    Set sslCert to <REFERENCE_IMPLEMENTATION>/samples/javaclient/certs/server/node.crt
    Set sslCaCert to <REFERENCE_IMPLEMENTATION>/samples/javaclient/certs/ca/ca.crt

**IMP: Do not use ~ to denote the home directory. Use the absolute path instead. So, instead of ~/documents/samples, use /home/pi/documents/samples.**
