### ISSUE TITLE
BUILD FAILURE when trying to run the client using mvn exec:exec

### ISSUE THREAD

**Issue by Satch97** [amzn/alexa-avs-raspberry-pi#148]
Good Day!

I(Raspberry Pi newbie) have been working on this project and have been troubleshooting this issue for a few hours.

![updatingjavatroubleshoot5](https://cloud.githubusercontent.com/assets/15304104/14714415/df143e18-07b2-11e6-9f44-1dfba4992d15.png)

mvn validate and mvn install are both successful. The error message is very vague, and I have checked the config files and been unable to find any error

Originally we had the wrong timezone on our Raspberry Pi and in order for the certificates to be generated we entered a location not in our time zone. Has the time zones caused the mvn exec:exec to be an issue for anyone else?

Any help or guide to solve this problem would be appreciated!!!!

**Comment by itzmrdavis2u** [comment]
At a guess I would triple check your config file because that is where the error is. On lines 8,9 and 10 it says the file does not exist. Either the config is wrong or the file is not there?

**Comment by Satch97** [comment]
After double checking the config files, specificall the config.json, I realized that one line was in the wrong line so I fixed it and that error message was gone however the build failure persists. Thie current response is shared in the screenshot below. Thank you for your helps so far! My partner and I still work to get it through these last few steps. Any more suggestions would be helpful!

![updatingjavatroubleshoot6](https://cloud.githubusercontent.com/assets/15304104/14758731/b053302c-08d7-11e6-8401-75bd659cc601.png)

**Comment by Vd10101** [comment]
Check your config.json file.
I had the exact same error.
Turns out I was messing up with string quotes in config.json
I fixed the typo and everything runs fine now

**Comment by ajotwani** [comment]
@Satch97 you still having this issues?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by Satch97** [comment]
I apologize for not responding within the timeframe at all. However the error lied within our settings on the amazon developers page(project names were not done correctly) and that resolved the problem. I suppose editing the config.json file a  @Vd10101 would also work.
