### ISSUE TITLE
5.0 Install the dependencies

### ISSUE THREAD

**Issue by Rubenkr3** [amzn/alexa-avs-raspberry-pi#149]
I can't install the dependencies because if I type `npm install` I get this awnser: `bash: nvm: Command not found.`

**Comment by mansong1** [comment]
I ran into the same problem, even though I had node installed. 
I had to run this to fix it: _sudo apt-get install nodejs npm node-server_

**Comment by Rubenkr3** [comment]
I fixed it. 
Thanks for your comment @mansong1.
