### ISSUE TITLE
Microphone Problems

### ISSUE THREAD

**Issue by Eddie-Hartman** [amzn/alexa-avs-raspberry-pi#150]
I bought the microphone linked in the readme to use for this project. The kinobo usb microphone on Amazon. The java client only pics up the mic if you YELL DIRECTLY INTO THE MIC FROM AN INCH AWAY (caps to portray annoyance of necessity to yell). I've mic boosted, played with gain controls, etc. I have another mic that works perfectly fine, but is much more expensive. Has anyone else had success with this mic? How? Mine is an issue to the point that it always stops listening during longer commands because it thinks I'm not talking, but the command will work. For example, if I say "What is the weather like in Columbus Ohio?" it will just get "What is the weather l....". Did I just get a bad model? After some googling I saw a lot of people having issues with this mic so we may want to change the recommended mic if there are really so many issues. It obviously wasn't expensive so it's not a huge loss, but it may reduce the amount of complaints in the long run if a lot of people have issues with this specific mic.

**Comment by ajotwani** [comment]
@Eddie-Hartman have you checked this thread - https://github.com/amzn/alexa-avs-raspberry-pi/issues/31?

**Comment by Eddie-Hartman** [comment]
#31 that does not apply to my issue. My issue isn't with playback, it's with recording/capturing. The audio is really low and noisy. It's been getting the job done, but I recommend using a different model microphone in the documentation because mine has issues with input. You have to almost yell to give long commands because Alexa thinks that you are not talking and stops listening. I had to mess with my audio settings just to get it usable and like I said it works, just not very well. I saw other people having input issues as well and think it may be due to the lower quality microphone, but they may be mislead to thinking that they did not configure something properly. I may have gotten a bad microphone too.

**Comment by ajotwani** [comment]
Aha. Gotcha. Mind sharing the settings you ended up using? We can perhaps add that to the FAQ section.

**Comment by Eddie-Hartman** [comment]
I basically just went into Audio Device settings and turned the capture volume all the way up and turned gain control on. Hopefully that helps someone.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by JeffHoover** [comment]
The same discussion is going on in this thread: https://github.com/alexa/alexa-avs-sample-app/issues/64 

I had the same experience with the suggested Kinobo Mic. It has basically no gain, even when I turn off the auto gain and set mainual gain to max with alsamixer. A poster there suggested right-clicking on the audio icon in the taskbar and adjusting settings there. I haven't tried that yet.
