### ISSUE TITLE
Child error when trying to Extract the contents of the tarball to the /opt directory.

### ISSUE THREAD

**Issue by adehyzler** [amzn/alexa-avs-raspberry-pi#153]
Linux ARM 32 Hard Float ABI
  	jdk-8u91-linux-arm32-vfp-hflt.tar.gz
Error is not recoverable
Can anyone help, thanks.

**Comment by BFP20** [comment]
I found a solution to the same error just now: https://github.com/amzn/alexa-avs-raspberry-pi/issues/98
It's happening because you need to be in the Downloads folder in Terminal. Hope this helps.

**Comment by adehyzler** [comment]
Many thanks
Much appreciated
Ade

**Comment by ajotwani** [comment]
Same as #98. Closing as resolved.
