### ISSUE TITLE
Java soft float no longer on Oracle ?

### ISSUE THREAD

**Issue by NX3** [amzn/alexa-avs-raspberry-pi#154]
Java SE Development Kit 8u91 and 8u92 Linux ARM 32 Hard Float ABI are the only versions listed. Is it ok to use these rather than the older 77 soft float versions ?

**Comment by NX3** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u77-oth-JPR

No soft float version 8u77

**Comment by samknight** [comment]
I used the hard float version and it worked fine

**Comment by NX3** [comment]
Indeed it does, got it working lastnight but it would be good if the instructions were updated.

**Comment by ajotwani** [comment]
Ah, this is annoying. Oracle seems to keep changing those file names alternating between soft/hard every couple weeks.

**Comment by ajotwani** [comment]
Updated Read me to reflect the comment above. Fixed with https://github.com/amzn/alexa-avs-raspberry-pi/commit/0721ac2ca78f41654f5384b47a479be8ff34606f
