### ISSUE TITLE
Just use these Python scripts

### ISSUE THREAD

**Issue by Kimsipi** [amzn/alexa-avs-raspberry-pi#155]
https://github.com/lennysh/AlexaPi

**Comment by itzmrdavis2u** [comment]
@Kimsipi these Python scripts are good and easy to use however they are based on AVS V1 api which dosn't support timers and alarms etc.. this one is base on the new AVS api

**Comment by ajotwani** [comment]
Like @itzmrdavis2u said, that project is currently using AVS v1 API. For a complete list of features supported by the new AVS API, including support for timers and alarms, please see this https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/avs-api-overview
