### ISSUE TITLE
No Audio Cue

### ISSUE THREAD

**Issue by SoupOfBob** [amzn/alexa-avs-raspberry-pi#156]
For: 10 - Obtain Authorization from Login with Amazon 
Step 6 says:
"Click the Start Listening button and wait for the audio cue before beginning to speak. It may take a second or two for the connection to be made before you hear the audio cue."

My problem is, I don't hear any audio cue.  Here's what I can tell you:

* My listener says it is listening on port 3000- so presumably that's OK.
* Running mvn exec:exec starts up the application.  I've got a Bearer Token and I've  validated with Amazon..

* When I speak in the microphone the grey "sound bar" in the Alexa Voice Service lights up to indicate it heard me.  (the microphone is on the same USB dongle as the sound out).

* I never hear a response back from Alexa and I don't see anything on the terminal that says my voice inquiry is sent.  If I leave it listening for a long time and then hit stop-listening I get a "Bad Request" exception on the terminal.  Presumably I'm breaking the rule for length of request. Otherwise it doesn't register that the request was sent at all on the terminal.

Anyone any suggestions.

**Comment by wunc** [comment]
Same problem. I know the audio out is working because I can play an mp3 with omxplayer and vlc, but I never hear any feedback from the Alexa client, neither an audio cue nor an audio response. Just silence.

**Comment by picmax** [comment]
I think I have the same problem with a USB sound card.

**Comment by ajotwani** [comment]
@wunc @picmax @SoupOfBob do you guys hear the audio cue when you click "Start listening"?

**Comment by picmax** [comment]
@ajotwani Yes, I finally fixed it. The key item is to edit the boot config file to prevent the loading of default sound module. The 2nd key item is the .asoundrc file. Edited like the video by Tony D!
