### ISSUE TITLE
OS not Raspbian error when upgrading Java version

### ISSUE THREAD

**Issue by ashi2014** [amzn/alexa-avs-raspberry-pi#161]
In Step 9, when upgrading my Java version by running the command ./install-java8.sh, I am getting an error "OS not Raspbian, exiting...". However, I confirmed that my OS is correct by going to /etc/os-release, which shows the OS is Raspbian Wheezy v7.

Any ideas why this is occurring? Also, is this step mandatory if I already have Java v1.8.0 installed? I haven't been able to get the app to work (see my comment in issue #125) and am wondering if this might be the cause.

**Comment by dansaia** [comment]
I have the same issue and can't seem to find an answer anywhere...did you get this fixed and if so please explain how.  Thank you.

**Comment by whysh** [comment]
Same issue:
The issue appears to be in alexa-avs-raspberry-pi/samples/javaclient/install-java8.sh
which appears to verify that the OS is raspbian via the following:
Not sure the ramification of commenting out those lines.

alexa-avs-raspberry-pi/samples/javaclient/install-java8.sh
# Ensure we are running on Raspbian
lsb_release -a 2>/dev/null | grep Raspbian
if [ "$?" -ne "0" ]; then
    echo "This OS is not Raspbian. Exiting..."
    exit 1
fi

pi@raspberrypi:~/alexa-avs-raspberry-pi-master/samples/javaclient$ uname -a
Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux

pi@raspberrypi:~/alexa-avs-raspberry-pi-master/samples/javaclient$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.10 (wheezy)
Release:	7.10
Codename:	wheezy


Any help???

**Comment by whysh** [comment]
I commented out the following lines in the installer and was able to make it through step 10.

lsb_release -a 2>/dev/null | grep Raspbian
if [ "$?" -ne "0" ]; then
echo "This OS is not Raspbian. Exiting..."
exit 1
fi

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
