### ISSUE TITLE
Smart Home Discover Devices no UPNP trace

### ISSUE THREAD

**Issue by kbarto323** [amzn/alexa-avs-raspberry-pi#162]
I have not been able to get Echo Pi to integrate into my Indigo Home Automation via a Phillips Hue Bridge plugin which it should recognize natively.  I tried a packet capture and am not seeing the Echo Pi UPNP discovery.  Does anyone know if this code supports Smart Home integration?

**Comment by itzmrdavis2u** [comment]
I have had this issue as well. I have a feeling discovery has not been enabled. I have been trying to use echo ha-bridge but alexa on pi will not find it however my friend who has a proper echo finds it straight away. would be nice to have this confirmed and get some info as to whether this feature will becoming soon,

**Comment by keleric** [comment]
Discovery is not currently a feature offered by AVS

**Comment by kbarto323** [comment]
Thank you for the update – that explains why I couldn’t make it work!

**Comment by benblb** [comment]
Erik from Echo support suggested I try using IFTTT to control Hue and it worked perfectly! Great workaround.
