### ISSUE TITLE
"Bad Request"

### ISSUE THREAD

**Issue by jrlambs** [amzn/alexa-avs-raspberry-pi#166]
I got everything up and running, companion server starts up.. I can validate... and get to the point where the GUI is running and has the authorization token entered.  I believe I'm having trouble with the sound/microphone though.  I'm using a Pi3 with the same microphone recommended by the readme.  

At first when I started the item would listen for a few seconds and stop and basically do nothing.. I assume it could only hear silence and give up and never made a request.  As suggested in another thread I made sure my USB microphone was the selected audio device. (https://github.com/amzn/alexa-avs-raspberry-pi/issues/39) but that didn't seem to help. I then followed the instructions in that same post to change some values in the java src file.  

ENDPOINT_THRESHOLD 6 
ENDPOINT_SECONDS 6

Now, if I open the sound mixer every time and select the USB Microphone and then press the "Start Listening" and talk.. it will stop listening after a bit and "make a request" but it fails with a "Bad Request" message.

`com.amazon.alexa.avs.exception.AlexaSystemException: Bad Request
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:34) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:314) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:284) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:60) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:214) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:210) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:29) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:220) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:60) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:491) [classes/:?]
02:22:16.988 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.exception.AlexaSystemException: Bad Request
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:34) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:314) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:284) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:60) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:214) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:210) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:29) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:220) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:60) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:491) [classes/:?]`

I'm using
Pi3
16GB SD card
Ethernet Connected
wifi turned off
pi is both plugged into a speaker via 3.5mm port on the pi and hooked up to a TV via HDMI.... the beep sound seems to be coming from the 3.5 mm jack output.
logitech wireless keyboard.. using a USB dongle.
microphone recommended in the readme.

I do have a hardware button hooked up to GPIO18 and Ground and I've tried the Python Alexa stuff using that hardware button and it works fine.  I make sure I stop the python stuff before I start the java client.

I'm out of ideas. Any thoughts?

**Comment by markbeee** [comment]
Did you try to record and play sound with alsa-utils tools like arecord and aplay with the forementioned microphone? (Tutorial e.g.: http://www.g7smy.co.uk/?p=283)

**Comment by jrlambs** [comment]
ah, so that's interesting.  I definitely used arecord to record something while I was in the GUI and it worked.   I'm testing remotely now..... and I'll test in the GUI again later.. but I followed the tutorial.. when it got time to record I started some music playing in the same room as the pi and triggered the arcord program and.. nothing.  the meter at the bottom sits at 0% and even though I set a duration of "10" it never actually "Stops" recording.. I do get a file with a non-0 size though so it's doing something.. just seems like the microphone isn't picking up any sound... I did verify that there is indeed sound playing in the room though via a webcam :)

**Comment by jrlambs** [comment]
I went back to the auto gain control setting and hit "M" again so it now show "OO"  now the meter at the bottom hovers between 0 and 1%... I have the recording volume set to 86% right now though.

**Comment by markbeee** [comment]
Try to test a different mic - even if it is from a webcam. I tested like five microphones now which were totally different in recording speech (sounds).

**Comment by jrlambs** [comment]
yeah, it's just weird that the python code that talks to alexa uses this microphone just fine.. I can talk and alexa responds as expected... it's just odd.

which appears to also use alsaaudio like this

 inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, "plughw:1")
                                inp.setchannels(1)
                                inp.setrate(16000)
                                inp.setformat(alsaaudio.PCM_FORMAT_S16_LE)
                                inp.setperiodsize(500)

**Comment by Ikol18** [comment]
Guys please help
Everything is setup perfectly with oracle java 8, maven ,node and everything
When I click on start listening the bar indicates its listening but when I press stop its not giving output
please help me
useful info:
using rpi2
usb sound card with mic input and speaker output(both are in working condition)
node v 5.10.0 and npm v3.8.3

**Comment by jrlambs** [comment]
this is basically the behavior I was seeing before I started getting the "Bad Request" I'd say it almost certainly has to do with the microphone not actually hearing anything.  I'd start with this thread and try some of the things there.

https://github.com/amzn/alexa-avs-raspberry-pi/issues/39

In particular make sure your microphone is the selected input.. and you can try updating the java program to wait for a little more silence before submitting the request.

Also in the main walkthrough he has a FAQ at the bottom of it with the number one question being "I got the Raspberry Pi working with AVS, but I can’t hear the audio response from Alexa"  so you could try what he recomments under that

**Comment by jrlambs** [comment]
I'm still working on this.  The python program can somehow record sound fine, but I can't get arecord or the java program to hear anything.  As sad as it is, I don't have access to another microphone... not even a webcam... so I keep beating my head against the wall with the little USB one I got....  I have considered replacing the USB microphone with a USB sound card and finding a decent 3.5 mm plug microphone.. but I'm having trouble deciding what is the best way for me to go... all i care about is  that the sound out of the sound card is a little better than the current 3.5mm jack on the pi3 and the microphone do a good job of picking up my voice from about arms-reach away..... I would be curious if people had suggestions there.

**Comment by wedob13** [comment]
Guys i am having issue with the output too. I hear the cue sound. I talk. It says prosessing for ever. It does not do anything after that. Any ideas?

**Comment by Ikol18** [comment]
See this
[https://github.com/amzn/alexa-avs-raspberry-pi/issues/156](url)

**Comment by wedob13** [comment]
i am getting 404 page error :)

**Comment by Ikol18** [comment]
You mean the while authenticating to amazon website???

**Comment by wedob13** [comment]
No no. I mean the link you send me prompts at 404 error page. I cant open it
Στις 6 Μαΐ 2016 21:54, ο χρήστης "Ikol18" <notifications@github.com> έγραψε:

**Comment by Ikol18** [comment]
Go here
#156 
#163 
#83

**Comment by wedob13** [comment]
Thank you ver much!
Στις 7 Μαΐ 2016 10:15 πμ, ο χρήστης "Ikol18" <notifications@github.com>
έγραψε:

**Comment by jrlambs** [comment]
Here's an update on what's happening.  I finally got arecord to pick something up.... if I turn off "Auto Gain Control" it records nothing. ever.   If I turn auto gain control on, and talk loudly... I get arecord to show it picking up at about 3%.  I did use the microphone from the guide.. and I think I've heard other people have the complaint about the weak pickup of it... but like I said.. the python version of the program seems to work fine. I'm not positive that there's anything else to try at this point though.

**Comment by keleric** [comment]
Are you still seeing this issue? If you are, can you get the x-amzn-requestids (in the HTTP header) for the request?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
