### ISSUE TITLE
alexa-avs-raspberry-pi npm error

### ISSUE THREAD

**Issue by Tippedsaint** [amzn/alexa-avs-raspberry-pi#168]
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/pi/alexa-avs-raspberry-pi-master/samples/javaclient/ca/ca.crt'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/home/pi/alexa-avs-raspberry-pi-master/samples/companionService/bin/www:23:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log

**Comment by ajotwani** [comment]
Have you seen this? https://github.com/amzn/alexa-avs-raspberry-pi/issues/123

**Comment by Tippedsaint** [comment]
I'm a little new to this, so how do I run the npm debug log. Sorry if this is kind of a stupid question.

**Comment by Tippedsaint** [comment]
So I looked around in my files and I think it's cause ca.crt and node.crt don't contain anything for my files

**Comment by Tippedsaint** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart alexa-voice-service-sample-companion-service@1.0.0
7 info start alexa-voice-service-sample-companion-service@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
10 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
12 verbose cwd /home/pi/Desktop/samples/companionService
13 error Linux 4.1.19-v7+
14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
15 error node v0.10.44
16 error npm  v2.15.0
17 error code ELIFECYCLE
18 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
18 error Exit status 8
19 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
19 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node ./bin/www
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs alexa-voice-service-sample-companion-service
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls alexa-voice-service-sample-companion-service
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by swasey-amzn** [comment]
Originally the error looks like the ca.crt file didn't exist. Did you create it, or did you run the generate script to create them? What changed between your original error log and the most recent?

**Comment by jjlink** [comment]
It appears like I have the same issue. 

The log file is attached.
[npm-debug-log.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/255455/npm-debug-log.txt)

**Comment by keleric** [comment]
Has this been resolved?

**Comment by leochirag** [comment]
That error is caused due to error generating a self-signed certificate. Try running sudo ./generate.sh after setting chmod permissions for generating the certificate. And then try running npm again.
I'm guessing the error shouldn't pop-up now.

**Comment by sidharthrajaram** [comment]
(https://cloud.githubusercontent.com/assets/14987538/16248411/dcda7dd8-37c3-11e6-9082-35162a2c5d88.png)

For some reason, I get a similar error but after saying "Error: ENOENT, no such file or directory" it gives no indication of the said file. What seems to be the issue?

**Comment by sidharthrajaram** [comment]
I solved this error by referencing the correct filepaths for sslKey, sslCert, and sslCaCert. All should be within the /companionService/certs/ directory.

**Comment by ajotwani** [comment]
Closing as resolved.
