### ISSUE TITLE
mvn exec:exec issue, Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

### ISSUE THREAD

**Issue by rayfsthird** [amzn/alexa-avs-raspberry-pi#172]
Hi all]

My Pi is a bit wonky. This is the error message I'm getting:

exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/opt/alexa-avs-raspberry-pi-master/samples/javaclient/target/classes/, file:/root/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/root/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/root/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/root/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/root/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/root/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/root/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/root/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/root/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar, file:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/root/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/root/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/root/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/root/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/root/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/root/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/root/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:230)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:129)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:14)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:86)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:89)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.418 s
[INFO] Finished at: 2016-05-08T05:28:07+00:00
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 

I guess it's having trouble finding some Java stuff but I can't parse the meaning of this error sufficiently to solve this myself.

**Comment by 1nput0utput** [comment]
@rayfsthird, looks like you don't have VLC installed, make sure it's installed.
https://github.com/amzn/alexa-avs-raspberry-pi#24---install-vlc

**Comment by gaurav-lagad** [comment]
Hi, @1nput0utput. I am facing the exact same issue, I tried reinstalling java, vlc and maven to resolve this issue but had no luck. Can you please let me know what I might be doing wrong? Thank you!

**Comment by 1nput0utput** [comment]
Hey @gaurav-lagad, you might wanna check if the VLC library is installed ```ldconfig -p | grep vlc``` 
Make sure you have the correct version of Java installed as mentioned in the guide, by running the following commands you can select the version you've extracted in your /opt directory:
`sudo update-alternatives --config javac`
`sudo update-alternatives --config java`

**Comment by gaurav-lagad** [comment]
Hi @1nput0utput . Thank you so much for your input. Unfortunately, I tried out everything that you have told and the documentation mentions. Here is a list of things that I have done till now: 
1)I tried installing java , vlc once again. Tried setting the path once again for vlc, no luck. 
2)I tried installing jdk 1.8.0_77 instead of 1.8.0_91(the latest one). Still no luck. 
Here are the outputs for the above commands: 
```
 ldconfig -p | grep vlc
        libvlccore.so.8 (libc6,hard-float) => /usr/lib/libvlccore.so.8
        libvlc.so.5 (libc6,hard-float) => /usr/lib/libvlc.so.5
```
 
For the update-alternatives command, it gives the output as nothing to configure. 

```
java -version 

java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) Client VM (build 25.77-b03, mixed mode)

```
```
javac -version

javac 1.8.0_77
```

Also, java has been installed from SE Development Kit, arm32 hard float. 

Can you please tell me what I can do to get the things right ? Thanks

**Comment by 1nput0utput** [comment]
@gaurav-lagad can you paste the stack trace you're getting in here.

**Comment by gaurav-lagad** [comment]
Hi @1nput0utput, I resolved the issue. The issue was, the jna jar was not being downloaded. I changed the pom file and got the issue resolved. Thanks a ton for your help!

**Comment by 1nput0utput** [comment]
Glad to hear that, @gaurav-lagad.

**Comment by pi0089** [comment]
Hi @gaurav-lagad - i have the same error message you had. Can you share the steps you took to resolve? Including your updates .pom.xml - thanks!

**Comment by gaurav-lagad** [comment]
Hi @pi0089. I think you are running it on RPi. Add this in the dependencies section :
```
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>4.1.0</version>
  <scope>compile</scope>
</dependency>
```
Let me know if you need the entire file.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by Knight1** [comment]
Hey, I have the same problem on my Pine64. I already copied libvlc.so and libvlccore.so to /usr/lib/vlc for testing purposes. But that didn't fixed the problem. Any ideas?

**Comment by koolkarni** [comment]
Add "sudo" when you do mvn

**Comment by dcwang1224** [comment]
Hi , I got the same problem and had copied libvlc.so and libvlccore.so to /usr/lib/vlc.
And meanwhile I did all compile as root but didn't fixed this problem. Any suggestion ?
but my ldconfig -p | grep vlc are as below version:
root@localhost:/# ldconfig -p | grep vlc
        libvlccore.so.7 (libc6,AArch64) => /usr/lib/libvlccore.so.7
        libvlc.so.5 (libc6,AArch64) => /usr/lib/libvlc.so.5
Did I need to get libvlccore.so.8 ?

**Comment by SamrudhaK** [comment]
@gaurav-lagad 
I (a novice RPi user) am getting a similar problem while running the app on Raspberry Pi3. 
Can you pls explain step by step how did you solve the problem?

Here is the errror msg shown in the cmd window.

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (linux-arm/libvlc.so) not found in resource path ([file:/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes/, file:/home/pi/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/pi/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/pi/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/home/pi/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar, file:/home/pi/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar, file:/home/pi/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar, file:/home/pi/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar, file:/home/pi/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar, file:/home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar, file:/home/pi/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar, file:/home/pi/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar, file:/home/pi/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/home/pi/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar])".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
	at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:252)
	at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:143)
	at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:183)
	at com.amazon.alexa.avs.App.<init>(App.java:47)
	at com.amazon.alexa.avs.App.<init>(App.java:36)
	at com.amazon.alexa.avs.App.main(App.java:31)

**Comment by ltrain5000** [comment]
I was able to recitfy this issue after beating my head against the wall for hours and hours and making seemingly pointless fixes. It is working perfectly now and it has nothing to do with the code.

Go back into your Amazon Developers Account where you follow these steps:
"In the textbox, next to Allowed Origins enter: https://localhost:3000
In the textbox, next to Allowed Return URLs enter: https://localhost:3000/authresponse"

Once you input the text, click "update" before you hit "save". If you don't do this, the permissions are not saved and it causes the error. You must visually verify the permissions are stored, or you will not be able to proceed past the step you are describing. I believe this is why the solution to this problem is so murky. It has nothing to do with the error you are receiving. I was having this problem in both Pi Alexa projects and I realized I made the same mistake on both by erasing everything, deleting each alexa product, starting totally over and confirming I followed all steps thoroughly. It works perfectly now on both. I hope this helps.

**Comment by nunezmanny** [comment]
adding "sudo" as suggested by koolkarni did it for me: sudo mvn exec:exec 
Thanks!

**Comment by kknaveenkumar** [comment]
I was facing the same issue, but after I have installed libvlc-dev package, the error was resolved. Try below in the terminal:
sudo apt-get install libvlc-dev

**Comment by HollowedEmpire** [comment]
@kknaveenkumar Wow, that fixed the issue I had. Thanks a lot for sharing that!

**Comment by Bcommft** [comment]
@kknaveenkunar That solution almost works for me as well!  I say almost because I do not see a smaller response window to finish my registration process generated. Did I miss part of your post?  Have you encountered this?  If so how to correct it?

Bosquin
