### ISSUE TITLE
Failed to start companion service client

### ISSUE THREAD

**Issue by punitganshani** [amzn/alexa-avs-raspberry-pi#177]
I'm getting this error in Companion Service client:

```
Failed to start companion service client
BadRequest: The provided product and dsn do not match valid values
```

I believe the `config.json` file was rightly configured but is there any way to figure the expected values?

**Comment by ajotwani** [comment]
Added an FAQ for "Companion Service" errors. See https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors. Scroll all the way down.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by abhisheksimion** [comment]
When I run mvn exec:exec following https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi guide I am getting below exception

`04:30:53.682 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: The provided sessionId is not ready to use.
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:179) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:94) [classes/:?]
`
 This redirects me to Dev Authorization page, confirming that you’d like your device to access the Security Profile created earlier. Once I click on agree I get  below page error

`
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.`

Any idea on how to resolve this issue?

**Comment by jmcbri** [comment]
Same here it's something with the session id

**Comment by altitudeinfosys** [comment]
I am having the same problem. Tried the same installation process on PI 2 and still no success. I am getting:

04:30:53.682 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: The provided sessionId is not ready to use. at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?] at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:179) ~[classes/:?] at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?] at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?] at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?] at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:94) [classes/:?] 
This redirects me to Dev Authorization page, confirming that you’d like your device to access the Security Profile created earlier. Once I click on agree I get below page error

 We're sorry! An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

**Comment by aberonni** [comment]
I was having the same problem.

I think this is incorrect in the [sixth chapter](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#6---run-the-sample-app) of the Windows documentation:

> In your favorite text editor, open `{REFERENCE_IMPLEMENTATION}/samples/javaclient/config.json` and edit the following values:
> 
> `productId`: Enter my_device as a string

I solved this issue by entering the `productId` defined in [chapter 1.b](https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#b-create-a-device-and-security-profile) of the documentation instead of "my_device as a string".

**Comment by m-faridi** [comment]
aberonni has it correct.
Your Device id and your DSN must match for both the Companion Service and the Java client app. 

Make sure that you get the Device ID from your Amazon setup.

**Comment by lslamp** [comment]
Guys, people have been working on automating the startup of alexa and as a result of this, the issue has reappeared. Below is my config.json and I get the error 

   "productId":"RasberryEcho",
    "dsn":"RasberryEcho",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":true,
    "avsHost":"https://avs-alexa-na.amazon.com",
    "autoLoginEnabled":true,

Lawrence

**Comment by m-faridi** [comment]
Where is the recipe for automation?

**Comment by ayubmalik** [comment]
I had the same problems but managed to get round them by setting all the values for product id/dsn/serial to my device id in AWS .

So in AWS I created a device with DEVICE ID  **arubalinux** and then ran the following steps  (Please note I have cloned this repo into my ~/source directory)

In file `~/source/alexa-avs-sample-app/samples/javaclient/config.json` set both
productId and dsn to **arubalinux**.

regenerate the keys by running `~/source/alexa-avs-sample-app/samples/javaclient/generate.sh` and set product id and serial number to **arubalinux**

Edit file ~/source/alexa-avs-sample-app/samples/companionService/config.js and set the products to above e.g. 

 products: {
        "arubalinux": ["arubalinux"], // Fill in with valid device values, eg: "testdevice1": ["DSN1234","DSN5678"]
    },


Then continue with rest of instructions. Worked for me!

**Comment by charliegilliland** [comment]
@m-faridi I have submitted a PR for an auto-login feature here: #431. It hasn't been merged though. From what I can tell the SessionID error and my code are unrelated, but the SessionID error is thrown from the companionService/authentication.js file and I am not familiar enough with JavaScript to identify the specific problem. 

My working thesis is that the SessionID error is caused when the SessionID that you are currently trying to use (it can be found in javaclient/config.json) has already been used before (for example if you are trying to use the same ClientID and ClientSecret on two different devices simultaneously).

**Comment by Archetype90** [comment]
@ayubmalik I had this same issue, and was able to fix it by doing your suggested fix. Something may need to be updated in the documentation to reflect this, as doing different product/DSN did not seem to work.
