### ISSUE TITLE
Shutdown & restart procedures?

### ISSUE THREAD

**Issue by Shazster** [amzn/alexa-avs-raspberry-pi#178]
Is there a specific restart procedure for shutdown, device reboot, and resuming the services, (assuming my initial build and Amazon sign on was correctly done)?

(NB: I am running this on an HP Mini 2133, Lubuntu 14.04

**Comment by ajotwani** [comment]
@Shazster you may want to check this thread - https://github.com/amzn/alexa-avs-raspberry-pi/issues/48. 

Closing this as duplicate.
