### ISSUE TITLE
No npm

### ISSUE THREAD

**Issue by t-barban** [amzn/alexa-avs-raspberry-pi#189]
Am installing on a Rpi3. Everything is going is exactly as instructed except I got a response of v0.10.29 when testing for node prior to installing node.js so I skipped that install.
At npm install step npm is not found. I am in the companionService directory. Any suggestions?

**Comment by ajotwani** [comment]
@t-barban I'd recommend  following the steps for Node install, so run the following on the terminal - 

sudo apt-get update 
sudo apt-get upgrade
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install nodejs 

Let us know if that fixes it. Thanks!

**Comment by t-barban** [comment]
That fixed it thanks.

Fantastic job of making the project accessible for a noob

**Comment by ajotwani** [comment]
@t-barban That's great to hear. Let us know what you end up building :)
