### ISSUE TITLE
npm fails to start

### ISSUE THREAD

**Issue by chuckplumber** [amzn/alexa-avs-raspberry-pi#190]
Hi folks, I'm pretty new to Linux and this one I can't figure out. Can someone please offer a suggestion?  I'm actually installing this onto a photo frame that I made out an old laptop and is running ubuntu linux, not a raspi. 

jeff@photoframe:~/Alexa/samples/companionService$ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/jeff/Alexa/samples/companionService
> node ./bin/www

sh: 1: node: not found

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jeff/Alexa/samples/companionService/npm-debug.log
jeff@photoframe:~/Alexa/samples/companionService$ 

Error log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/jeff/Alexa/samples/companionService/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/apache-maven-3.3.9/bin
10 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: /home/jeff/Alexa/samples/companionService
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '-c', 'node ./bin/www' ]
12 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
13 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
15 verbose cwd /home/jeff/Alexa/samples/companionService
16 error Linux 4.4.0-22-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
24 error spawn ENOENT
25 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     node ./bin/www
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs alexa-voice-service-sample-companion-service
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls alexa-voice-service-sample-companion-service
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

Thanks much

**Comment by 4430salton** [comment]
you have to use the absolute path.  do not use ~ symbol but rather something like this
use 
/home/Alexa/samples/companionService$npm start

not this path ~/Alexa/samples/companionService$ npm start

would be my suggestion.  later

**Comment by chuckplumber** [comment]
Thanks. I was starting from the /home/jeff/Alexa/samples/companionService directory
and used the command:
jeff@photoframe:$ npm start

I didn't use the shortcut. or am I missing something?

**Comment by chuckplumber** [comment]
Figured it out. I searched npm troubleshooting on google. Got this page.  https://github.com/npm/npm/wiki/Troubleshooting
Did node -v
Said node is not installed.... I had installed it at least twice as part of my own ts
Followed these instructions to install node:
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

I think that perhaps the instructions in the article are old?

curl -sL https://deb.nodesource.com/setup | sudo bash -
Install Node itself:

sudo apt-get install nodejs 

Anyhow, it is solved. On to the next steps

**Comment by 4430salton** [comment]
been out of town.  Glad you figured it out! and thanks for the info too
