### ISSUE TITLE
AVS on Armv7 device

### ISSUE THREAD

**Issue by gaurav-lagad** [amzn/alexa-avs-raspberry-pi#192]
Hi,
The sample app works excellent on a ubuntu machine. I want to run the sample app on armv7 device(So basically I want to communicate with Alexa from an armv7 device). So, I am trying to resolve the dependencies as much as I can. We will have our own driver through which we can play sound( I guess that should remove the vlc dependency). We have openssl built on our device which helps us generate keys. We are building a jetty version which will be suitable for our compact java(cvm). 
However, we are stuck at getting nodejs installed on our device. Can you please provide any information with the help of which I can install nodejs or maybe suggest a workaround? Your help is highly appreciated on this issue. Thanks!!! Do let me know if you need any information from my side.

**Comment by swasey-amzn** [comment]
Node.js is only necessary to run the sample companion service. It doesn't need to run on the same device as the actual AVS client. You could have it running on a separate machine (your Ubuntu machine, perhaps), as long as they're both accessible from each other.

You could also go the companion application route, which is a one time setup and puts a refresh_token on the AVS client device which never expires, so it'll be able to make requests to LWA and retrieve new access_tokens without the need for any extra service or application to be running. Instructions for that process can be found on this page and section: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/java-client-sample#Building%20and%20Running%20a%20Node.js%20Server%20or%20%20Mobile%20App

Just select Android or iOS as appropriate.

**Comment by gaurav-lagad** [comment]
Thanks! @swasey-amzn

**Comment by ajotwani** [comment]
Closing as resolved.
