### ISSUE TITLE
Exception in thread "main" javax.json.stream.JsonParsingException:

### ISSUE THREAD

**Issue by hankp46** [amzn/alexa-avs-raspberry-pi#197]
Getting the following error when  running  mvn exec:exec
.path=$(env.VLC.PATH) com.amazon.alexa.avs.AVSApp
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 103 at (line no=8, column no=34, offset=259), expecting 'l'

Checked  config.json pom.xml and config.js and can't see any typos.  
Any idea where I should look?

**Comment by ANANDSKRISHNAN** [comment]
how this error get recified? plz tell
