### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by kevinwidjaja21** [amzn/alexa-avs-raspberry-pi#204]
I have a problem when starting npm. However, it seems to be a different problem.
![capture](https://cloud.githubusercontent.com/assets/19798208/15856415/7877815e-2cdf-11e6-825a-3aa2bc595cf2.PNG)

sorry if the probblem seems simple for you. I am new with raspberry pi.

**Comment by chrispc05** [comment]
You have a typo in your config.js file. Your sslCert line is missing a slash "/" It needfs tyop end with ..."server/node.crt" Check to see if this slash character was omitted when you edited the file.

**Comment by ajotwani** [comment]
Closing as resolved.
