### ISSUE TITLE
error on amazon page when try to register

### ISSUE THREAD

**Issue by KavishBhatia** [amzn/alexa-avs-raspberry-pi#205]
![screenshot from 2016-06-07 17-55-04](https://cloud.githubusercontent.com/assets/8553451/15857454/294a3866-2cd9-11e6-917a-50e8c2474eb3.png)
can you tell me what is the problem?

**Comment by illperipherals** [comment]
In the developer console at https://developer.amazon.com:
 - click on the Alexa tab and then the AVS button.
 - Select the device under Registered Products, and click the Edit button on the far right.
 - Click on Security Profile on the left, then on the Web Settings tab.
 - Click the Edit button in the upper right, and add an entry under Allowed Return URLs to match the return address (e.g. https://localhost:3000/authresponse )
 - Click Save.

I think this is probably what is causing your error.

**Comment by KavishBhatia** [comment]
I have added this URL while following the steps.

**Comment by illperipherals** [comment]
Was that not the issue?

**Comment by kevinwidjaja21** [comment]
I also have this problem. I have follow this alexa tutorial and novaspirit tech tutorial and i still have same problem. Sorry but i am new with raspberry pi so i don't know what is wrong.

**Comment by kevinwidjaja21** [comment]
Sorry, i also have been having this problem for some ie. I have both follow the official step and novvaspirit tech and still get this problem. I will try different tutorial later as troubleshooting with both tutorial yields no improvement.

**Comment by kevinkey619b** [comment]
I added the allowed URLs, but it looks like I'm still being banned by Amazon?
