### ISSUE TITLE
No need to suggest 64 bit java.

### ISSUE THREAD

**Issue by stayupthetree** [amzn/alexa-avs-raspberry-pi#21]
While yes the chip on the Raspberry Pi 3 is 64 bit, Raspbian is only 32bit, thus errors come from telling Raspberry Pi 3 owners this "Raspberry Pi 3 model - The binary you are looking for is “Linux ARM 64 Soft Float ABI”. Download the tar.gz file jdk-8u77-linux-arm64-vfp-hflt.tar.gz from the Oracle link above."

They still need to use the 32bit.

**Comment by stayupthetree** [comment]
http://linuxgizmos.com/raspberry-pi-3-has-a-64-bit-cpu-but-a-32-bit-raspbian-os/

**Comment by cyborg-girl** [comment]
Thanks. Installing 64-bit java had messed up things for me on RPi3.

**Comment by ajotwani** [comment]
Fixed with https://github.com/amzn/alexa-avs-raspberry-pi/commit/8721be63a240e7e1f24379604ae52df9ddefb25b
