### ISSUE TITLE
Cannot hear flash update

### ISSUE THREAD

**Issue by hankp46** [amzn/alexa-avs-raspberry-pi#211]
I can ask questions and AVS responds but when I ask for flash update it responds with "Here's your flash update" then no audio. If I let it go it will finally come back with "News Flash update has ended". I have removed and reinstalled VLC but result is the same.

I can also get the flash update file from the log and play it through VLC.

**Comment by LakesGeek** [comment]
Just wondering if you got this working?  I'm having the same issue.

**Comment by LakesGeek** [comment]
Got it - default volume seems to be 0, if you tell Alexa "volume 8" then you can hear it.  Been scratching my head over this for hours!
