### ISSUE TITLE
mvn exec:exec  vs. sudo env "PATH=$PATH" mvn exec:exec

### ISSUE THREAD

**Issue by hankp46** [amzn/alexa-avs-raspberry-pi#218]
I'm attempting to add the push button code to this project (see issue #14). In my testing I have not been able to hear radio stations or flash updates. To use the push button you need to run mvn as:
sudo env "PATH=$PATH" mvn exec:exec.
I then ran my code without the push button mod with mvn exec:exec and it worked fine (hear flash and radio). I then ran the same code with sudo env "PATH=$PATH" mvn exec:exec and no radio or flash.

I surmise that something with sudo env "PATH=$PATH" mvn exec:exec is causing the problem but cannot find it.

Added info: with the sudo command debug points to p:/root/.m2......
                    with the mvn exec:exec debug points to p:/home/pi/.m2.......
Any clues?

**Comment by Eddie-Hartman** [comment]
This may not be helpful, but it could possibly have something to do with your folder structure. I have my alexa... folder in /home/pi. Is that where yours is? I can listen to radio stations and get news on mine and it shouldn't be a code issue since I changed so little.

**Comment by hankp46** [comment]
It's definitely not a code issue. I agree that it's probably a path problem but I also have Alexa in home/pi.I think it has to do with not being able to get to/play VLC since that is what is used to play flash while questions use the Speech Synthesizer.

**Comment by hankp46** [comment]
I never did get this problem solved but found out that the new Pi4J package allows you to use GPIO without having to run with sudo. Made those changes and all is now working!
