### ISSUE TITLE
 Java Development Kit (JDK) issue - Any Ideas?

### ISSUE THREAD

**Issue by renyats71** [amzn/alexa-avs-raspberry-pi#22]
pi@raspberrypi ~ $ sudo tar zxvf jdk-8u73-linux-arm32-vfp-hflt.tar.gz -C /opt
tar (child): jdk-8u73-linux-arm32-vfp-hflt.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by moodybass** [comment]
Did you download the tar first?  I think that command will need running from the directory you downloaded the tar too - if you downloaded using the GUI, it's probably ~/Downloads

**Comment by renyats71** [comment]
Many thanks - Rookie error!!!
