### ISSUE TITLE
Change default location from Seattle?

### ISSUE THREAD

**Issue by tomhannen** [amzn/alexa-avs-raspberry-pi#222]
Alexa seems to think I'm in Seattle.  Is there a way to tell it that I'm not?
Thanks for a great idea by the way :)

**Comment by hfjensen** [comment]
If you go into the Alexa companion app on your smartphone you can change the location in settings.

**Comment by tomhannen** [comment]
Ah, just tried that... I don't think the Amazon Alexa iOS app is available in the UK yet...

**Comment by Thelle** [comment]
It seems that it is possible to access the settings on the web too: http://alexa.amazon.com - haven't tried it myself, but heard it should work.

**Comment by tomhannen** [comment]
Good to know!  Got this error when I tried anything in the UK... Guess I'll have to wait.  Thanks all!

![image](https://cloud.githubusercontent.com/assets/185299/16563449/06e996e6-41fa-11e6-8ce2-4558b0d235dd.png)

**Comment by ajotwani** [comment]
Closing as answered.

**Comment by sw11mike** [comment]
I found a great set of instructions on another forum for changing the location and measurement units. These worked for me to change my location to London, UK:

http://www.echotalk.org/index.php?topic=228.0

**Comment by destroy-everything** [comment]
Can you document where these setting are stored?
