### ISSUE TITLE
Server doesn't run

### ISSUE THREAD

**Issue by gabe817** [amzn/alexa-avs-raspberry-pi#23]
I followed the Alexa-Raspberry Pi procedure and everything seemed to go as expected until I got to Step 8 - Run the Server.  When I execute the "npm start" command nothing happens.  It just goes back to the prompt.  I tried to move on to step 9 in case the server was actually running without me knowing it.  The "chmod" command appears to complete successfully but I got a command not found error when trying to execute the "./install-java8.sh" command. Anybody have any suggestions as to what the problem is?  (I'm installing on a Raspberry Pi B+).

**Comment by KevinHanson** [comment]
Try npm start –loglevel info

 

That’s dash dash loglevel.

 

Please share the output if it works. Hopefully you can see an error message with the log level set.

**Comment by gabe817** [comment]
Unfortunately, executing "npm start --loglevel info" gives the same result. It just goes back to the prompt.

**Comment by ghctim** [comment]
sounds like your NPM install isn't working.  can you try doing an apt-get install npm

**Comment by gabe817** [comment]
When I try to execute the "apt-get install npm" command it says "Some packages could not be installed. This may mean you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming."  It then lists a bunch of packages that have unmet dependencies and ends with "Unable to correct problems, you have held broken packages".

Should I try another apt-get update?

**Comment by cwilkes** [comment]
@gabe817 try doing `sudo apt-get install npm` but anyway `npm start` complains later that it should really use a newer version and to run `sudo npm -g install npm@latest-2` 

You might want to also try doing a `sudo apt-get remove npm`

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by Uvissa** [comment]
I still have the same problem. I have tried everything above to no avail.

**Comment by Uvissa** [comment]
When i type npm start, I get a command not found error
