### ISSUE TITLE
Question about where the program runs java methods that represent what an intent does

### ISSUE THREAD

**Issue by UltimateOgee** [amzn/alexa-avs-raspberry-pi#230]
Say that I am running AVS on a computer that is registered as an AVS device. Right now I have managed to run the hello world sample app provided in these files in java on that machine, as that device is registered under the same account for which I made the skill.

I want to run the following code on the computer that is running as an AVS device when a certain intent is called by the user:
String command = "sudo python /home/Desktop/script5";
Process p = Runtime.getRuntime().exec(command);

Would putting this code inside a method representing an intent work? Or is all this code working in the cloud.. not in the computer running as an AVS device.

If the second condition is the case, what is the best way for me to run that code snippet given that an intent is called by the user?

Your help is greatly appreciated!

**Comment by keleric** [comment]
That depends - what intent are you trying to run that script on? The routing of directives to the places that handle them is in AVSController.java.

**Comment by UltimateOgee** [comment]
Update: What my main goal is to run a command on the command line of a linux computer on my LAN based on code running in lambda.
