### ISSUE TITLE
How to start service again after installation?

### ISSUE THREAD

**Issue by TravisBumgarner** [amzn/alexa-avs-raspberry-pi#233]
Complete noob issue but there's no mention of how to do this in the article.

**Comment by sinfulangle** [comment]
Travis, did you work this out because I too am having the same issue.

**Comment by bat013** [comment]
I'm trying to auto script it but the only way that i have found this to work is repeat the following steps. essentially skipping all install commands but doing the rest after step 9:
cd /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService
npm start
open new terminal
cd /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient
mvn exec:exec

then go to the website and click ok

**Comment by sinfulangle** [comment]
bat013, I do exactly the same. I wish it was a little more automated on startup.

**Comment by ajotwani** [comment]
Closing as resolved.
