### ISSUE TITLE
4.3.4 ALPN version compatibility OpenJDK

### ISSUE THREAD

**Issue by bat013** [amzn/alexa-avs-raspberry-pi#234]
Hello All, 

I'm having an issue where i cannot update the pom file with the correct ALPN version because the table listed in the instructions doesn't go high enough. i cannot find the matching version. Does anybody know where i can find it? 

provided table: http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions
my installed versions
java: 1.8.0_101
javac: 1.8.0_101

**Comment by bat013** [comment]
see updated table:
http://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html#alpn-versions

**Comment by rbirt** [comment]
both of the tables linked above only go up to JDK version 1.8.0u102

i am using JDK version 1.8.0_111, does anyone know what  or where i can find the matching alpn version?

**Comment by truxntrax** [comment]
I have the same question and same issue - did you resolve this?

Thanks

**Comment by rbirt** [comment]
I resolved it by installing version 1.8.0u91 which you can get at Oracle's JDK archive site.

**Comment by DaAwesomeP** [comment]
According to [here](https://mvnrepository.com/artifact/org.mortbay.jetty.alpn/alpn-boot) it might be `8.1.10.v20161026`.
