### ISSUE TITLE
Amazon music is not supported for this device?

### ISSUE THREAD

**Issue by sinfulangle** [amzn/alexa-avs-raspberry-pi#235]
Hi guys,

Firstly I'd like to say great tutorial! Very easy & simple to follow.

I am wondering if there is some way we can get the Pi to play music using Alexa. When I ask it to play a song it says:

"Amazon music is not supported for this device".

Thanks

**Comment by swasey-amzn** [comment]
When on the developer portal and you're creating your Product you can select to enable your device to support Amazon Music and then fill out a short form. Once that form is filled out our people internally will evaluate and send you an email if it is enabled for you.

**Comment by ajotwani** [comment]
Closing as resolved.

**Comment by howardguo** [comment]
Where and How to do this step bellow?

When on the developer portal and you're creating your Product you can select to enable your device to support Amazon Music and then fill out a short form. Once that form is filled out our people internally will evaluate and send you an email if it is enabled for you.

**Comment by rickey527** [comment]
Is there no way to go back and do it after the fact? Or some way to delete your device and start over...

**Comment by xaos11** [comment]
@rickey527 Amazon Music on AVS-Sample-App appears to only be supported if you are a developer actively working on a device. Music was cut-off for all security profiles that don't fit this description:
"Amazon Music is currently limited to Alexa-enabled devices that are approved for commercial distribution and use. "
https://forums.developer.amazon.com/questions/57317/how-long-is-it-currently-taking-for-avs-amazon-mus.html
