### ISSUE TITLE
Errors when start npm

### ISSUE THREAD

**Issue by EloittER028** [amzn/alexa-avs-raspberry-pi#249]
Hello, I've got a problem when I try to start npm, a bunch of errors occurs....
Here what it says:
pi@my_device:~/Desktop/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-mast
er/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient/certs/server/node.key'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-raspberry-pi-master/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by Ztnepres** [comment]
I did a refresh reinstall on a different pi and got this. My older setup doesn't spit an error but doesn't respond after clicking start listening. Strange

**Comment by EloittER028** [comment]
Emm yeah I could re-do it from the beginning but I was hoping for some faster solutions... I guess it's just a typo somewhere but I don't know where...

**Comment by Ztnepres** [comment]
I got mine working. Try going back to Step 4: Make sure your JDK ALPN versions match. The JDK is no longer 1.8.0_91 but 1.8.101

**Comment by EloittER028** [comment]
No it's ok it works now, it was a dumb thing :  the folder of the project was located in another folder with the same name, so the computer was unable to find the way to nodekey. So I just had to copy the content of the subfolder and paste it in the first folder .
