### ISSUE TITLE
No pop up window when opening client for first time

### ISSUE THREAD

**Issue by billybidley** [amzn/alexa-avs-raspberry-pi#26]
When I opened the client for the first time a didn't get a pop up window saying "Please register your device by visiting the following website on any system and following the instructions: https://localhost:3000/provision/d340f629bd685deeff28a917 Hit OK once completed." So it therefore doesn't work. Anyone have any ideas?

**Comment by vlasov01** [comment]
I had the same issue. First, enable more logging by starting the client with more debug information:
`mvn -e -X exec:exec`
In my case I had an earlier version of Java. It start working after the upgrade to Oracle JDK 1.8.0_77-b03.

**Comment by billybidley** [comment]
I've tried updating, and it now at 1.8.0_77-b03 but it still does not work. I've enabled debugging and haven't seen any obvious errors. I now get an error message saying "line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported." Thank you for your help.

**Comment by vlasov01** [comment]
I had the same issue. I've tried all kind of things, but a workaround I've end up was just running it as root:
`sudo mvn -e -X exec:exec`

**Comment by stayupthetree** [comment]
Just a quick question, are you running it from a terminal on the Pi itself, or logged into SSH from another computer?

**Comment by billybidley** [comment]
I've tried both, neither seem to have worked, I'm trying a fresh install now

**Comment by stayupthetree** [comment]
Well when you get it setup again and want to start it up from a remote shell, 'export DISPLAY:0' will have any GUI elements open on the desktop of the Pi

**Comment by billybidley** [comment]
Now I think I've figured out the problem, but not too sure how to rectify it. Whenever I do the "npm" command i get the response "illegal instruction"

**Comment by billybidley** [comment]
I thought it may have been something to do with the Nodejs installation, but I've just reinstalled it and it still throws up the same error. Could it be that I'm using a raspberry pi model 1?

**Comment by ajotwani** [comment]
@billybidley can you please confirm if you are still having this issue? Also, have you looked at this thread? https://github.com/amzn/alexa-avs-raspberry-pi/issues/50

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
