### ISSUE TITLE
Docker image for quicker setup?

### ISSUE THREAD

**Issue by cowchimp** [amzn/alexa-avs-raspberry-pi#27]
Hi. Any chance to offer a Docker image with some of this setup preconfigured?

**Comment by bgulla** [comment]
im working on one. I'll submit a PR once i get it working.

**Comment by Cloudmage** [comment]
Great idea. Look forward to that.

**Comment by stretch00777** [comment]
Thank you.  I hope I hear about it when its done.

**Comment by bgulla** [comment]
https://github.com/bgulla/rpi-alexa-docker/blob/master/Dockerfile

Doesn't fully work yet. I should be able to finish it tomorrow. Watch the repo for updates.

**Comment by stretch00777** [comment]
I'm just trying to help....this will run docker containers on the Pi.  What
are you using?Hypriot Docker Image for Raspberry Pi

http://blog.hypriot.com/downloads/

**Comment by stretch00777** [comment]
never mind.  I sent email before looking at GitHub.  Thank you for your
effort.
