### ISSUE TITLE
error on line 1 of ssl.cnf

### ISSUE THREAD

**Issue by renyats71** [amzn/alexa-avs-raspberry-pi#30]
Any idea what's wrong with the following ssl.cnf config? Many thanks in advance. 

[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=pi
countryName             = YOUR_COUNTRY_NAME                 # C=GB
stateOrProvinceName     = YOUR_STATE_OR_PROVINCE            # ST=Somerset
localityName            = YOUR_CITY                         # L=Yeovil
organizationName        = YOUR_ORGANIZATION                 # O=renyats71
organizationalUnitName  = YOUR_ORGANIZATIONAL_UNIT          # OU=kailua3108

**Comment by duncangeere** [comment]
I believe you need to replace "YOUR_COUNTRY_NAME" with "GB", and so on below.

**Comment by ghctim** [comment]
yes, you need to replace everything in your YOUR_ lines

**Comment by phamhp** [comment]
i give up. After changing and changing the ssl.conf file, i am still getting the error: 
--------------------------------------------------------------------------------------------------------------------------
Product ID: my_device
Serial Number: 123456
Password for Keystores (won't echo): Generating RSA private key, 4096 bit long modulus
..............++
...................................................................................................................................................++
e is 65537 (0x10001)
error on line 14 of ssl.cnf
1995581536:error:0E065068:configuration file routines:STR_COPY:variable has no value:conf_def.c:618:line 14
Generating RSA private key, 2048 bit long modulus
.+++
..................+++
-----------------------------------------------------------------------------------------------------
I guess my ssl.cnf is wrong but i dont know what wrong. Here is my ssl.conf, please let me know what wrong. Thank you!

[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::pham # CN=pham
countryName             = US # C=US
stateOrProvinceName     = California # ST=California
localityName            = Garden_Grove # L=Garden_Grove
organizationName        = myself # O=myself
organizationalUnitName  = one # OU=one

**Comment by chasedg2008** [comment]
change prompt = yes, it will ask you to type in the values for each of the above when you run the request. This is how i got it working.

**Comment by ajotwani** [comment]
@phamhp here's what the ssl.cnf file would look like, replacing country, state, locality with your respective info - https://gist.github.com/ajotwani/a0d54110a968c984fd0b

**Comment by phamhp** [comment]
@chasedg2008 @ajotwani thanks guys for the update. I will confirm the result when I have time after work. Maybe today night or tomorrow night.

**Comment by renyats71** [comment]
I think i've followed @ajotwani's sample ssl.cnf file correctly? @chasedg2008 @duncangeere duncangeere

[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = GB                 # C=
stateOrProvinceName     = Somerset            # ST=
localityName            = Yeovil                         # L=
organizationName        = YOUR_ORGANIZATION                 # O=
organizationalUnitName  = YOUR_ORGANIZATIONAL_UNIT          # OU=


However, I still get:

pi@raspberrypi ~/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient $ chmod +x generate.sh
pi@raspberrypi ~/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient $ ./generate.sh
Product ID: my_device
Serial Number: 123456
Password for Keystores (won't echo): Generating RSA private key, 4096 bit long modulus
................................................................................................................++
..........................++
e is 65537 (0x10001)
error on line 1 of ssl.cnf
1996028000:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:362:line 1
Generating RSA private key, 2048 bit long modulus
................................................+++
....+++
e is 65537 (0x10001)
error on line 1 of ssl.cnf
1995458656:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:362:line 1
certs/client/client.csr: No such file or directory
Error opening input file certs/client/client.crt
certs/client/client.crt: No such file or directory
Generating RSA private key, 2048 bit long modulus
..............................+++
....................................................+++
e is 65537 (0x10001)
error on line 1 of ssl.cnf
1995966560:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:362:line 1
certs/server/node.csr: No such file or directory
Generating RSA private key, 2048 bit long modulus
..........+++
..........................................+++
e is 65537 (0x10001)
error on line 1 of ssl.cnf
1996011616:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:conf_def.c:362:line 1
error on line 1 of config file 'ssl.cnf'
Error opening input file certs/server/jetty.crt
certs/server/jetty.crt: No such file or directory
cp: cannot stat ‘certs/ca/ca.crt’: No such file or directory
Error opening Certificate certs/ca/ca.crt
1996261472:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('certs/ca/ca.crt','r')
1996261472:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
cp: cannot stat ‘certs/ca/ca.der’: No such file or directory

**Comment by chasedg2008** [comment]
try filling out your Org Name and Org unit, Also make sure the spacing is correct. I had issues with the original ssl.cnf file so i restored it and left the original spacing at the end of each value i changed. You can see a picture of an ssl.cnf at the bottom of the instructions page.

**Comment by phamhp** [comment]
follow the ssl.cnf example mentioned on the comment above of @chasedg2008. No more generating error.

**Comment by ajotwani** [comment]
Here's what the ssl.cnf file should look like - https://gist.github.com/ajotwani/a0d54110a968c984fd0b. Also included this link in the ReadMe and the FAQ section - https://github.com/amzn/alexa-avs-raspberry-pi/commit/613a2abeb11a7e172c57eb111bf61af6433c3cad

**Comment by shaolinkhoa** [comment]
hi @ajot 

your link https://gist.github.com/ajotwani/a0d54110a968c984fd0b died
It should be https://github.com/ajot/alexa-avs-raspberry-pi/blob/master/samples/javaclient/ssl.cnf , right ?

**Comment by lvan-jone** [comment]
@renyats71  Did you solve the problem? I encountered the same problem

**Comment by jackfruh** [comment]
For anyone else who encounters this, make sure your file encoding is UTF-8 - a number of text editors can tell you this, and change the format if it's something else.

**Comment by bilalmuhammad-ips** [comment]
Did anyone solve this issue? I copied the conf file verbatim and still getting the error and the file is indeed UTF-8

**Comment by bilalmuhammad-ips** [comment]
I fixed it by changing **commonName = $ENV::COMMON_NAME # CN=pi** to **commonName = whatever # CN=**
