### ISSUE TITLE
Sound too low when starts speaking 

### ISSUE THREAD

**Issue by neroxyr** [amzn/alexa-avs-raspberry-pi#31]
When I ask Alexa something, the sound at first is too low, but then I can hear good. Is it normal to behave this way?

**Comment by ghctim** [comment]
turn up the sound in the upper right corner of x where the speaker is...

**Comment by neroxyr** [comment]
It is up, but the sound is low only the first seconds

**Comment by thomasleplus** [comment]
If you're using an HDMI monitor as your sound output, it might be the same as issue #38.

**Comment by neroxyr** [comment]
Thanks, will try the 3.5 mm configuration

**Comment by ajotwani** [comment]
@neroxyr can you confirm if you are still having this issue?

**Comment by neroxyr** [comment]
@ajotwani not anymore, used the 3.5 mm as output and I can hear everything. For the ones who have this problem check this tutorial https://www.raspberrypi.org/documentation/configuration/audio-config.md. Is it going to have a fix for this problem?

**Comment by ajotwani** [comment]
Closing as resolved.
