### ISSUE TITLE
no results printed in the terminal

### ISSUE THREAD

**Issue by haraldgsinger** [amzn/alexa-avs-raspberry-pi#32]
audio answer is playing OK, but I would like to see what was actually recognized.  For example, certain currency conversions work, but others don't, for example  "50 US Dollars in Euros" works, but it fails for "50 US Dollars in Jordanian Dinar" and I am wondering if this is a recognition or semantic analysis issu.
I have been running
    mvn -e -X exec:exec
but the last message on the terminal console was 
[DEBUG] Executing command line: java .... com.amazon.alexa avs.AVSApp
No printed results at all.

**Comment by haraldgsinger** [comment]
I am wondering, are others getting the printed results on the terminal? If so, with what command line?

**Comment by ajotwani** [comment]
@haraldgsinger you can visit alexa.amazon.com on your browser or iOS/Android app to see the log of what Alexa heard. You can also use the app to voice train it.
