### ISSUE TITLE
No need to install Java, since it is shipped with Raspian

### ISSUE THREAD

**Issue by Lucurus** [amzn/alexa-avs-raspberry-pi#33]
According to this [post](https://www.raspberrypi.org/blog/oracle-java-on-raspberry-pi/) Java is already installed.

**Comment by ekelly** [comment]
I believe the version of java on the Raspberry Pi contains a bug that the latest version of Java from Oracle doesn't have. If you're running into issues relating to certificate validation and keystore stuff, chances are good you're running into this bug.

**Comment by ajotwani** [comment]
Closing as resolved.
