### ISSUE TITLE
Does this work on the Model 3? - Update Docs

### ISSUE THREAD

**Issue by iamjake648** [amzn/alexa-avs-raspberry-pi#36]
I see no reason why this would not work on the Model 3, newer raspberry Pi with built in WiFi and Bluetooth. Why is that not included in the Docs?

**Comment by Bantammenace** [comment]
It worked for me on RPi3 latest Jessie having updated and upgraded.

**Comment by SetiZ** [comment]
just finished setting it and it works! \o/

**Comment by cyborg-girl** [comment]
works like a charm.

**Comment by n8fr8** [comment]
Anyone experiment with a Bluetooth push-to-talk device of some sort? 

http://zello.bcoda.com/codawheel

http://www.pryme.com/index.php?l=product_detail&p=2454
