### ISSUE TITLE
alexa skipping first second or two when it answers?

### ISSUE THREAD

**Issue by NShak** [amzn/alexa-avs-raspberry-pi#38]
Everything is running like its supposed to, except that alexa skips the first 2 seconds when it answers my question. for example if it didn't understand my question, i hear "...n't understand your question".

**Comment by ajotwani** [comment]
@Nshak you still experiencing this issues? What's your hardware setup?

**Comment by NShak** [comment]
yes. I have a Pi 2 connected to a monitor via HDMI, with a kinobo usb mic. not sure why its doing it still.

**Comment by thomasleplus** [comment]
I had the same issue with my HDMI monitor. It works fine using speakers.

PS: initially when plugging in the speakers, the Pi kept using the HDMI output. I had to force the 3.5mm jack analog output through raspi-config's advanced options.
