### ISSUE TITLE
NPM cannot install or start

### ISSUE THREAD

**Issue by dafoley** [amzn/alexa-avs-raspberry-pi#40]
As others have mentioned Raspbian Jessie come preloaded with Java which I suspect may be causing this issue.  When I do a npm install or npm start it returns the error Illegal instruction.  I've tried a clean install for Raspbian Jessie and also running Raspbian from Noobs (same OS?).   I've also tried running "sudo apt-get install npm" as someone else mentioned but "some packages could not be installed.. follow by "the following packages have unmet dependencies.." with about 30 lines of items that were not installed. Finally Unable to correct problems, you have held broken packages.

Any help would be appreciated!

**Comment by gregwa1953** [comment]
I had to load NPM as well, but I used the following command...
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash`
from the github site:
https://github.com/creationix/nvm

You might give that a try.

**Comment by gabe817** [comment]
Maybe I'm missing something here but doesn't that command you referenced relate to "nvm" and not "npm"?

**Comment by gabe817** [comment]
I'm having the same problem (see my post "Server doesn't run") but I don't get any error message when executing npm start.  It just goes back to the prompt with no response.  If anyone comes up with a fix I'd appreciate it if you would respond to my post as well.

**Comment by gregwa1953** [comment]
If I remember correctly, I had to (re)install both NPN and NVM.  I believe I used this command line...

curl -L https://npmjs.org/install.sh | sh

Hopefully this helps.

**Comment by gabe817** [comment]
Thanks, I'll try both commands this afternoon.  Do I need to uninstall anything before running these commands?

**Comment by gregwa1953** [comment]
I didn't have to uninstall anything when I did it, so I don't think you will.

**Comment by dafoley** [comment]
Thanks gregwa1953, I'm going to give this a try tonight.  And just to clarify both my errors are related to npm-.  Step 8 - Run the server and Step 5 - Install the dependencies.

**Comment by gabe817** [comment]
i ran both commands as you suggested. the first one for "nvm" seem to execute successfully. it instructed me to close the terminal and reopen it to enable nvm.
After running the second command I got this 

curl -L https://npmjs.org/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    449      0 --:--:-- --:--:-- --:--:--   612
100  6263  100  6263    0     0   7073      0 --:--:-- --:--:-- --:--:--  7073
tar=/bin/tar
version:
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Segmentation fault
You need Node.js to run this program.
node --version reports: 
with exit code = 139
Please install Node.js before continuing.

I tried reinstalling node.js by doing this -

sudo curl -sL https://deb.nodesource.com/setup | bash -

## Installing the NodeSource Node.js 0.10 repo...


## Populating apt-get cache...

+ apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
Error executing command, exiting

and this -

sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

I tried running "npm start" anyway and now get a Segmentation fault error.

Any suggestions?

**Comment by gabe817** [comment]
Is it a requirement to have started with Raspian Jessie?  I used my 
original microSD card that came with my Model B+ and I believe it had 
Raspian Wheezy on it.  I've been assuming that the update and upgrade 
commands would've brought Raspian up to date but maybe that's not the case.

**Comment by dafoley** [comment]
I gave up and ordered an Echo Dot using the Roger app on my iPhone.. :)

**Comment by gabe817** [comment]
When you add up the cost of the Pi, case, AC adapter, microSD card, WiFi 
adapter, etc. you get pretty close to the price of an Echo Dot.  Plus 
the Dot is in a nice package and is always ready to accept voice 
commands without a switch or having to clap your hands.  But then you 
miss out of the learning experience and all of the fun you have getting 
the Pi to work plus having the satisfaction of almost doing it yourself.

**Comment by cwilkes** [comment]
@gabe817 friendly tip for posting large blocks of text in github: 
```
put triple
backticks around
the block
```
and it will come out formatted like you expect it to be.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
