### ISSUE TITLE
Updating config.json 

### ISSUE THREAD

**Issue by RadianM** [amzn/alexa-avs-raspberry-pi#43]
In step 7.2 - Update config.json the screenshot shows a sessionid string (in companionService) yet the downloaded file doesn't have this entry. I'm wondering if this has any bearing on the problem I'm having connecting to the companionService in issue #35 ?

Whatever, the screenshot of the file contents is somewhat different to what we see when we load it into an editor.

**Comment by bill-orange** [comment]
I noticed this too. I don't think the missing line is an issue since I am up and running with the line missing.

**Comment by ajotwani** [comment]
@RadianM Thanks for bringing this up. We'll update the screenshot to reflect the ReadMe. Can you confirm if you are still having issues connecting to the companionService?

**Comment by RadianM** [comment]
Thanks @ajotwani I managed to connect OK using the supplied config.json

**Comment by ajotwani** [comment]
Screenshot updated. Fixed with https://github.com/amzn/alexa-avs-raspberry-pi/commit/16b616a7fa21d51832a6b80a631adbc98e90a4e4
