### ISSUE TITLE
there was a problem connecting to Companion service

### ISSUE THREAD

**Issue by chasedg2008** [amzn/alexa-avs-raspberry-pi#44]
I follow the setup instructions and get the following error after running mvn exec:exec with the companion service running in a different terminal listening on port 3000; 

There was no popup either, i get the java applet but can not authenticate because i didn't get the link.

**Comment by bill-orange** [comment]
Same thing here. mvn exec:exec fails with what looks like a password error.  I triple checked all my .js and .json entries.  I bet you did too.

Here's a link to my screen with the error.  Is this what you are getting?

https://onedrive.live.com/redir?resid=F1B60A320CA8CA65!77491&authkey=!ABKUKzgaT0suvl0&v=3&ithint=photo%2cjpg

Bill

**Comment by chasedg2008** [comment]
I'm getting a different error, everything builds fine. but when running mvn it continuously tries to connect. Saying 

There was a problem connection to Companion Service. Trying again in 2 seconds. And i can see the service running and listening on port 3000

**Comment by RadianM** [comment]
I'm getting that too chasedg2008, r.e. issue #35 The record button appears in the Java applet but no pop-up with a link to get Authentication from Amazon Web site. I assume that the "Companion service" that it tries to connect to every two seconds is our server running on port 3000?

**Comment by nicandsam** [comment]
Same here

**Comment by RadianM** [comment]
I've resolved my problem now - see issue #35 for details

**Comment by bill-orange** [comment]
I corrected a couple of typos an got to "There was a problem connection to Companion Service. Trying again in 2 seconds"  with no popup.  RadianM can you provide more detail on your solution that see #35 .  My ssl.cnf looks okay to my layman's eyes.  Can you post your solution more specifically?

**Comment by bill-orange** [comment]
I've resolved my problem now. I screwed up the ssl.cnf file.  At the end of the readme there is a sample.  Its an important read.

**Comment by chasedg2008** [comment]
i've resolved this issue as well.

**Comment by ajotwani** [comment]
Updated ReadMe to include a sample ssl.cnf file - https://github.com/amzn/alexa-avs-raspberry-pi/commit/613a2abeb11a7e172c57eb111bf61af6433c3cad

**Comment by samanthabretous** [comment]
If you read through this whole github issue and might still have an issue, take a step back. Make sure you have two terminal windows open. In the first one navigate to {REFERENCE_IMPLEMENTATION}/samples/companionService and run `npm start`. While in the second window navigated to {REFERENCE_IMPLEMENTATION}/samples/javaclient. Then `mvm install` followed by `mvn exec:exec`.

**Comment by ANANDSKRISHNAN** [comment]
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.

**Comment by ANANDSKRISHNAN** [comment]
[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = US                 # C=
stateOrProvinceName     = WA            # ST=
localityName            = SEATTLE                         # L=
organizationName        = AVS_USER                 # O=
organizationalUnitName  = AVS_USER          # OU=

**Comment by ANANDSKRISHNAN** [comment]
plz help

**Comment by mz496** [comment]
It's also worth killing any lingering instances of node with `ps aux | grep node` and `kill -9 <pid>` for the pid's associated with `node ./bin/www` and `sh -c node ./bin/www`. This was my issue, that port 3000 was already in use.

**Comment by gurugudi** [comment]
Wanted to check if this is resolved by Anandkrishnan. I am still struggling. Did everything include reinstall, rebuild, checked SSL config. Still same error
"There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running."

The companion server is running fine in another window.

**Comment by ANANDSKRISHNAN** [comment]
Can u plz paste your config files ??

**Comment by gurugudi** [comment]
Config.js
***************
***************

/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.
 *
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.
 *
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: "XXXXXXXXXXXXXXX",
    clientSecret: "YYYYYYYYYYYY",
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/node.key",
    sslCert: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/node.crt",
    sslCaCert: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt",
    products: {
        "RPi": ["123456789"],
    },
};

module.exports = config;

***************
***************



config.json
***************
***************
{
    "productId":"RPi",
    "dsn":"123456789",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":true,
    "locale":"en-US",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt"
    }
}

***************
***************

**Comment by ANANDSKRISHNAN** [comment]
In my case the pblm is with dsn the format of dsn was Wrong

**Comment by NicoSoftware** [comment]
I'm having the same Problem .. npm start is running successfully on port 3000 (can't reach it with localhost/Ip:3000) and mvn exec:exec has no connection to the companion Service.
What can I do? 
In my network is running another webserver on Port 8080, could that be the Problem?

**Comment by NicoSoftware** [comment]
Config.js
Duplicate of /**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: "****",
    clientSecret: "*****",
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/node.key",
    sslCert: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/node.crt",
    sslCaCert: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt",
    products: {
        "RaspberryPi": ["123456789"],
    },
};

module.exports = config;#

Config.json:

{
    "productId":"RaspberryPi",
    "dsn":"123456789",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":true,
    "locale":"de-DE",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt"
    }
}
