### ISSUE TITLE
server doesn't start "Exit status 8"

### ISSUE THREAD

**Issue by pfmd86** [amzn/alexa-avs-raspberry-pi#46]
Hi, i have problems when i try to start the server. Got the following message:

> npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
> npm ERR! Exit status 8
> npm ERR!
> npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
> npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 4.1.19-v7+
> npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
> npm ERR! cwd /home/pi/alexa/alexa-avs-raspberry-pi-master/samples/companionService
> npm ERR! node -v v0.10.43
> npm ERR! npm -v 1.4.29
> npm ERR! code ELIFECYCLE
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/alexa/alexa-avs-raspberry-pi-master/samples/companionService/npm-debug.log
> npm ERR! not ok code 0

Any ideas?
I have an nginx server running on that maschine. But i allready killed the process. Same message!

**Comment by cyborg-girl** [comment]
I had the same problem, but I made it work. There is possibly a problem with your npm installation. First, use _sudo apt-get install npm_ followed by _npm -version_ to verify its installation.

restart the terminal, and 
_cd <REFERENCE_IMPLEMENTATION>/samples/companionService_
_npm install_
_npm start_

**Comment by pfmd86** [comment]
When i try to reinstall npm i got:

> pi@zombie04:~ $ sudo apt-get install npm
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  npm : Depends: nodejs but it is not going to be installed
>        Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
>        Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
>        Depends: node-ansi-color-table but it is not going to be installed
>        Depends: node-archy but it is not going to be installed
>        Depends: node-block-stream but it is not going to be installed
>        Depends: node-fstream (>= 0.1.22) but it is not going to be installed
>        Depends: node-fstream-ignore but it is not going to be installed
>        Depends: node-github-url-from-git but it is not going to be installed
>        Depends: node-glob (>= 3.1.21) but it is not going to be installed
>        Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
>        Depends: node-inherits but it is not going to be installed
>        Depends: node-ini (>= 1.1.0) but it is not going to be installed
>        Depends: node-lockfile but it is not going to be installed
>        Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
>        Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
>        Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
>        Depends: node-gyp (>= 0.10.9) but it is not going to be installed
>        Depends: node-nopt (>= 3.0.1) but it is not going to be installed
>        Depends: node-npmlog but it is not going to be installed
>        Depends: node-once but it is not going to be installed
>        Depends: node-osenv but it is not going to be installed
>        Depends: node-read but it is not going to be installed
>        Depends: node-read-package-json (>= 1.1.0) but it is not going to be inst                                                                              alled
>        Depends: node-request (>= 2.25.0) but it is not going to be installed
>        Depends: node-retry but it is not going to be installed
>        Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
>        Depends: node-semver (>= 2.1.0) but it is not going to be installed
>        Depends: node-sha but it is not going to be installed
>        Depends: node-slide but it is not going to be installed
>        Depends: node-tar (>= 0.1.18) but it is not going to be installed
>        Depends: node-underscore but it is not going to be installed
>        Depends: node-which but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.


Got the following warnings when installing again:

> pi@zombie04:~/alexa/alexa-avs-raspberry-pi-master/samples/companionService $ npm install
> npm WARN deprecated This version of npm lacks support for important features,
> npm WARN deprecated such as scoped packages, offered by the primary npm
> npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
> npm WARN deprecated latest stable version. To upgrade to npm@2, run:
> npm WARN deprecated
> npm WARN deprecated   npm -g install npm@latest-2
> npm WARN deprecated
> npm WARN deprecated To upgrade to the latest stable version, run:
> npm WARN deprecated
> npm WARN deprecated   npm -g install npm@latest
> npm WARN deprecated
> npm WARN deprecated (Depending on how Node.js was installed on your system, you
> npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
> npm WARN deprecated on Windows, run them from an Administrator prompt.)
> npm WARN deprecated
> npm WARN deprecated If you're running the version of npm bundled with
> npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
> npm WARN deprecated will be bundled with a version of npm@2, which has some small
> npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
> npm WARN deprecated semver behavior.
>

**Comment by ajotwani** [comment]
@pfmd86 Can you please confirm if you are still having issues?

**Comment by pfmd86** [comment]
I will retry the installation step by step this week and comment my issue again.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
