### ISSUE TITLE
Error with registering device

### ISSUE THREAD

**Issue by sudhirrssk** [amzn/alexa-avs-raspberry-pi#47]
Hi, 
I tried to follow the steps as said in the tutorial and I ended up getting everything running fine except at the end. When I tried to register my device to use Alexa i'm getting an error and not getting the "device tokens ready screen". Please find the snapshot of it below.
![image](https://cloud.githubusercontent.com/assets/18124966/14087891/4d449eb2-f4fa-11e5-97f6-f85f2346a1fa.png)
I am trying to revisit all the steps once again and appreciate any help in this regard.

Thanks,
Sud

**Comment by kentgeorgeson** [comment]
I have the same issue... could there be a service down at AWS?

**Comment by sudhirrssk** [comment]
Nope it has to do with the device id while creating the security profile. There is a solution listed in the below link and its works.

https://github.com/amzn/alexa-avs-raspberry-pi/issues/5

**Comment by JTG20** [comment]
Try making sure in the amazon developer edit online the URL you have entered is https:// not http:// as you will receive the error shown above

**Comment by krlbaker** [comment]
I get an error in the listen window that says error { [Error: Not Found] status: 404 } after I visit the link to authorize and get the device token.

**Comment by joetech** [comment]
@krlbaker Check your return URL
https://github.com/amzn/alexa-avs-raspberry-pi/blob/master/assets/avs-web-settings-filled.png

**Comment by krlbaker** [comment]
@joetech I double checked those setting and I copied from the page. Still getting that error after I authorize.

**Comment by krlbaker** [comment]
I figured out my issue, I had to run both the listener and the application as "sudo". Now everything is working!!

**Comment by OfficialLegend27** [comment]
Hey can you help me i have the same problem and no idea what to do...

**Comment by hannan112** [comment]
hi i am facing this problem pls help me
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.

**Comment by hannan112** [comment]
![capture](https://user-images.githubusercontent.com/41451097/43357152-08dfc314-9232-11e8-8c18-7728f73a89fe.JPG)
