### ISSUE TITLE
Got it running. Now what?

### ISSUE THREAD

**Issue by iacos** [amzn/alexa-avs-raspberry-pi#49]
The step by step tutorial is pretty straight forward even with no experience in Linux. I have it running after a couple of hours. Now, what can I do with it besides finding the weather or the date?
Can I play music on my PI? How? What service?
Can I start or voice control applications? Like a media player? Can I control these with Alexa?
Any suggestions for some fun would be much appreciated.

Thanks.

**Comment by sdcharle** [comment]
That's up to you. Use your imagination!

**Comment by iacos** [comment]
My question was "How do I do all these on my PI?" I need knowledge not imagination.

**Comment by AndersonQ** [comment]
Have a look at the [Alexa docs](https://developer.amazon.com/public/solutions/alexa)

**Comment by anjishnu** [comment]
You can write ASK skills to give it functionality you want it to have.

**Comment by ajotwani** [comment]
@iacos To begin with, you can visit alexa.amazon.com. Click on Skills and enable a few to play around with. Try searching for "Wayne Investigation", for instance!

**Comment by RadianM** [comment]
You can also connect to IFTTT and make all kind of things happen!
