### ISSUE TITLE
PCM_SIGNED

### ISSUE THREAD

**Issue by stiivik** [amzn/alexa-avs-raspberry-pi#50]
I get error at last step when alexa voice service runs. I press the button to listen, but i get error: " line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported"

Searched everywhere for this, but still nothing. All i got from different sources is that this is a java error. Tried using usb soundcard and usb headphones, still same. Would be really grateful for a solution!

**Comment by RadianM** [comment]
This is all that's holding me back now too.  I've yet to find an official specification from Amazon but I see people saying it has to be single channel PCM signed 16000Hz 16bit which is close to what wer'e seeing in the error message. I've tried a USB audio input lead and a webcam and both give exactly the same error.

**Comment by bill-orange** [comment]
I had the same error.  I switched to the internal PI analog audio instead of the USB adapter audio and that cleared it up.

Rerunning did not work for me.

**Comment by Kimberlyluve** [comment]
I agree

**Comment by Bantammenace** [comment]
No matter what I tried  I repeatedly got the error: " line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported". Thanks to an observation made by Hias  it appears that somewhere along the line a "rogue" asoundrc file has been acquired in /home/pi. I do not know where this file has come from. It is a hidden file which is listed when ls -la is used or ctrl H in the GUI file manager. Once I renamed this file all was well. I wonder if this is what others may be experiencing who get this error ? fyi I now have Alexa running using my Cirrus Logic Audio Card with its on-board mics. I installed the drivers following the instructions at www.horus.com/~hias/cirrus-driver.html

**Comment by bill-orange** [comment]
I had the identical error. 

I am using a USB sound device for connecting a mike with a 1/8" phone jack. I was routing the speaker out the same device. I moved the speakers back over to the analog out and the problem went away. 

You will need to change the audio preferences with the audio setting menu on the desktop to match your setup. I also discover you must hit 'set as default' for the change to work.

**Comment by ajotwani** [comment]
Closing as fixed.

**Comment by pcpeterchen** [comment]
I don't know why I'm getting this error.  Whenever I unplug and replug the microphone, it works.  But after a few commands it give the above error and I need to reset again.  I am using a USB microphone and analogue speaker.  Whenever I try to record with 
`arecord -d 10 -f S16_LE -r 16000 test.wav` it doesn't record.  

How Alexa is able to record a few commands but then throws the error.  Is it a problem with the mic or the pi?  This is a clean install.

**Comment by lslamp** [comment]
Peter,

I had something very similar, I have no idea how and what you are doing, but I was not following instruction very well. I was opening the first terminal and starting the companion, then opening a second terminal and starting the javaclient, but I was not waiting for the authentication process to complete fully, before closing the popup. When I realized what was going wrong, I then left the popup open until the authentication on the development portal was complete and only then did I close the popup. After doing this, all worked perfectly.

Lawrence

**Comment by faisalch** [comment]
was getting the above error when trying to run Alexa hands free
had a look at https://www.raspberrypi.org/documentation/configuration/audio-config.md

so ran raspbi config

even though i had espeak working, wakeWordAgent (sensory) didnt suport my audio setting. 
Ive a Raspiberry 3 , using Raspbian for Robots, a USB microphoen i pickd up off Amazon, and a small speaker connected to the 3.5 mm jack

within raspbi config i forced my audio setting to 3.5mm, ecen though i thought my Pi already was 

rebooted the pi

restarted Alexa services 

Launching Alexa

$ cd /home/pi/alexa-avs-sample-app/samples/companionService && npm start
$ cd ./alexa-avs-sample-app/samples/javaclient/

$ sudo mvn exec:exec
Here I login to Amazon
Java Applet launches - still manual mode
$cd /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src && ./wakeWordAgent -e sensory

and hey it worked !

**Comment by yeralin** [comment]
For those who want to use their USB Sound Cards, just follow this:
http://stackoverflow.com/questions/36208176/arecord-set-params1233-sample-format-non-available-available-formats-s16-l

**Comment by EpicLPer** [comment]
Sadly @yeralin's answer didn't fix it for me :(

**Comment by kleinfreund** [comment]
I can’t get the sample app to work via external audio card. I need to disable the internal audio card since I’m using PWM for an external display.

I fail to see how this issue is resolved as I don’t even know what’s wrong. The external speaker/microphone work fine on the Raspberry, just the sample app throws this error.
