### ISSUE TITLE
Maven 

### ISSUE THREAD

**Issue by mjt85nc** [amzn/alexa-avs-raspberry-pi#51]
I can't extract maven to /opt  following the directions. It says can't perform extraction! Don't have the right permissions to extract the files to the directory /opt. Am I doing something wrong?

**Comment by cyborg-girl** [comment]
try being the root, or change permissions for the /opt folder.

**Comment by mjt85nc** [comment]
I tried to change permissions it says completed with errors
Not sure what you mean they being root. I'm still learning lol

**Comment by dinimedia** [comment]
i tried making the file with nano,  but no noob love here either.

**Comment by KevinHanson** [comment]
@mjt85nc cyborg-girl means that at the terminal you would type sudo su - to become the root user. However the instructions for extracting the maven tar file are already advancing your rights using the sudo command

`sudo tar zxvf apache-maven-3.3.9-bin.tar.gz -C /opt`

actually if the tar.gz file downloaded to your Downloads folder the command would be like

`sudo tar zxvf /home/pi/Downloads/apache-maven-3.3.9-bin.tar.gz -C /opt`

good luck!

**Comment by mjt85nc** [comment]
I cant create maven.sh file in the  /etc/profile.d/maven.sh
it says permission denied. Any idea what im doing wrong? is there another way?

Step 3: Tell your shell where to find maven You’ll do this in the system profile settings so it is available to all users.

Create a new file /etc/profile.d/maven.sh, and type the following inside it:

export M2_HOME=/opt/apache-maven-3.3.9
export PATH=$PATH:$M2_HOME/bin
Save the file. Log out and back into the Raspberry Pi so the profile script takes effect. You can test that it is working with the following command:

**Comment by mjt85nc** [comment]
Is it sudo nano /etc/profile.d/maven.sh

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
