### ISSUE TITLE
Do I need a new mike?

### ISSUE THREAD

**Issue by bill-orange** [amzn/alexa-avs-raspberry-pi#52]
I found all my typos (I think) and figured out how to edit ssl.cnf correctly.  This got me to the point of getting a good bearer Token. 
I no know what the weather is like in Seattle.  I still have a problem however, Alexa only listens for a few seconds.  If I press START listening I have about two seconds before to blurt out my question before it goes back to STOP.  This If I ask What is the weather like in Los Angeles.  It has stopped listening before I get to the end of the sentence.

Do I need a new mike?

**Comment by Bantammenace** [comment]
Move to Seattle.

**Comment by bill-orange** [comment]
I considered that, but I am not a redwood.  By googling Alexa and settings you can find the web site where the user's zip code is set.  At least it knows where I am now. 

Others have reported the short 'mike-on' time in other threads.  I found that turning the mike gain all the way up helps.  The background noise appears to keep the mike listening.  This, however, is only a partial fix.  I think the software needs to be changed from the 4 second (?) wait time to about 10 seconds.
