### ISSUE TITLE
npm call returns "illegal instruction"

### ISSUE THREAD

**Issue by skradaroman** [amzn/alexa-avs-raspberry-pi#54]
When calling npm, I get "illegal instruction"

I get this on Raspberry Pi 2 model B.  Anyone else running into the same issue?
Running on:
Raspbian Jessie
Version:March 2016
Release date:2016-03-18
Kernel version:4.1

**Comment by bark100** [comment]
Same problem here on Raspberry Pi 1 Model B+ with:
Kernel 4.1.19+
Jessie 8.0
NodeJS 0.10.43-1nodesource1~jessie1

**Comment by crogger62** [comment]
Me too.
Kernel 4.19.1+

**Comment by AndyW7** [comment]
I had this problem but got past it and can get the Alexa app to load on my RPI 2 model B. I installed node.js following the guide at http://weworkweplay.com/play/raspberry-pi-nodejs/ follow step 2 and it gets node.js that works on the RPI 2s V7 architecture as this guide is primarily for the RPI 3 but this is the only thing I had to do differently.

**Comment by skradaroman** [comment]
@AndyW7 Thanks!  That worked.

**Comment by ajotwani** [comment]
Closing as fixed.
