### ISSUE TITLE
generate.sh fails

### ISSUE THREAD

**Issue by saurabh500** [amzn/alexa-avs-raspberry-pi#55]
While trying to use generate.sh the script fails with the following error 

openssl: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0: version `OPENSSL_1.0.1s' not found (required by openssl)

Any work around/resolution?

**Comment by pygold** [comment]
Hey saurabh, I am also facing the same issue. Did you found the solution for the above issue? if so, then kindly share it with us. Thanks!

**Comment by pygold** [comment]
Raspbian doesn't come with the development libraries for openSSL (libssl-dev), so you won't have support for this functionality.
try to install openssl development libraries first **sudo apt-get install libssl-dev**

Follow this link for more info
https://wiki.qt.io/Talk:RaspberryPi_Beginners_Guide#openSSL_Hint

**Comment by shoesandsocks** [comment]
@pygold , that did the trick for me. Thanks for the timely help!
