### ISSUE TITLE
ssl.cnf

### ISSUE THREAD

**Issue by mjt85nc** [amzn/alexa-avs-raspberry-pi#59]
how do i Change directories to <REFERENCE_IMPLEMENTATION>/samples/javaclient.

cd <REFERENCE_IMPLEMENTATION>/samples/javaclient - //your sample apps location
Step 2: Edit the text file ssl.cnf, which is an SSL configuration file. Fill in appropriate values in place of the placeholder text that starts with YOUR_.

Note that countryName must be two characters. If it is not two characters, certificate creation will fail. 

my alexa folder is in location 
                 /home/pi/alexa-avs-raspberry-pi/samples/javaclient

would i put in terminal 
cd /home/pi/alexa-avs-raspberry-pi/samples/javaclient

and from there im stuck. i can access ssl.cnf through the file manager  /home/pi/alexa-avs-raspberry-pi/samples/javaclient and open ssl.cnf. can i change the settings there or does it have to be in the terminal? Thanks

**Comment by stiivik** [comment]
You don't have to write "cd /home/pi/..." always. If You write just "cd" it throws You back into folder "pi" so You can just always go "cd alexa-avs-raspberry-pi/samples/javaclient" for instance. Also i recommend to change the folder name to something shorter, for example "alexa" as it's more convenient to write out. 

As for the ssl.cnf, You can change it with text editor from the file viewer and save it after the changes are done. I did it and worked for me. As i'm not on the name basis with linux, i don't know for sure, but i guess You could change it with "sudo nano alexa-avs-raspberry-pi/samples/javaclient/ssl.cnf"

**Comment by mjt85nc** [comment]
Thanks im trying it now

**Comment by mjt85nc** [comment]
ok so im adding my info relpacing YOUR
[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = YOUR_COUNTRY_NAME                 # C=
stateOrProvinceName     = YOUR_STATE_OR_PROVINCE            # ST=
localityName            = YOUR_CITY                         # L=
organizationName        = YOUR_ORGANIZATION                 # O=
organizationalUnitName  = YOUR_ORGANIZATIONAL_UNIT          # OU=

is common name pi?
organizationname?
organizationunitname?

**Comment by stiivik** [comment]
You don't have to change commonName, as there is no "YOUR_" there. As for the organizationName and organizationUnitName, i changed these to just "none". And be sure to type countryName as two characters. If You don't know Yours then this will help: http://www.worldatlas.com/aatlas/ctycodes.htm

After chaning these just hit save and You should be done with this part.

**Comment by mjt85nc** [comment]
Thanks again I appreciate it

**Comment by stiivik** [comment]
You're welcome!

**Comment by bill-orange** [comment]
I tried changing 'common name'.  If you do, the server wont allow a connection.  It took me a bit of time to figure that out!

**Comment by ajotwani** [comment]
Fixed with https://github.com/amzn/alexa-avs-raspberry-pi/commit/613a2abeb11a7e172c57eb111bf61af6433c3cad.
