### ISSUE TITLE
Null Pointer Exception - [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.   AVSApp - An error occured creating speach request

### ISSUE THREAD

**Issue by kentgeorgeson** [amzn/alexa-avs-raspberry-pi#62]
OK, been troubleshooting this for a while, but not sure where to go next.  CompanionService starts fine.   Start the JavaClient sample app and I get the dialog box.  We I hit the button to start listening, I get an Error dialog with no text.   The following error is written to the console....

![image](https://cloud.githubusercontent.com/assets/604430/14118233/385df566-f5ae-11e5-99d0-569376eac1e7.png)

**Comment by kentgeorgeson** [comment]
OK, sorted it out.  USB Microphone wasn't registered in ALSA.   Now works.

**Comment by stiivik** [comment]
@kentgeorgeson Hey, what do You mean by not registered in ALSA? What did You do to fix this or how should the microphone be configured?

**Comment by jbd0101** [comment]
Hey @kentgeorgeson , 
I have the same issue , What did you do to fix it ?

Thanks
JC
