### ISSUE TITLE
Suggested Kinobo Mic doesn't work.

### ISSUE THREAD

**Issue by aTanguay** [amzn/alexa-avs-raspberry-pi#64]
Has anyone had any issues with the suggested USB Microphone?

I was using the microphone on my webcam (logitech C310) with good results, but got this microphone in the mail today and the level is so low and staticky that Alexa can't understand what I'm saying.

I tried alsamixer and maxed it out, but now a test recording barely works...you can hear me, but just a bit behind the static.

People seem to like this one more as you can choose your microphone...

http://www.amazon.com/Adafruit-100265-USB-Audio-Adapter/dp/B00KAE2L1C/ref=sr_1_4?ie=UTF8&qid=1459285744&sr=8-4&keywords=raspberry+pi+audio

**Comment by jacksonrdlc** [comment]
Not sure about that one BUT I used this one because it was the best deal at Microcenter and it worked perfectly and its super cheap.

http://www.amazon.com/Cyber-Acoustics-Uni-directional-Microphone-CVL-1064/dp/B00006B9W6

**Comment by aTanguay** [comment]
Is this USB on the other end, or is it like 3.5mm jack?

Thanks!

**Comment by otherwayup** [comment]
Initially very disappointed with results; very limited success with recognition of what was said.  I'd bought a USB mic from the bay that looks just like the suggested kinobo one.

Then I saw the OPs link in first post above and remembered I had a similar external 3.5mm jack speaker/mic to USB adapter/card already.

Using this and cheap gaming headset with mic (3.5mm jack) I get much, much better recognition results; very good.  The level bar that grows from left to right during listening is much lower (hardly moves), but good results.

Only problem now is that after I click on Start Listening, it will only listen for about 2-3 seconds (blue light in my adapter starts flashing), then it stops listening as if I'd clicked on Stop Listening and Processes whatever it's heard.

Has anyone found the perfect USB mic. for this?

**Comment by MrJamesEllis** [comment]
Try the audio settings in the RP desktop. Right click on the audio icon in the taskbar and choose Device Settings. Pick the  Mic from the "Sound Card' drop down and fiddle with the Mic levels. Select Controls may also give you an Auto Gain Control for the Mic.

I'm using an old Logitech webcam as a USB Mic and it works well. I fiddled with the Mic settings after clicking Start Listening and you can  modify the capture volume to minimise background noise being picked up.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by JeffHoover** [comment]
I bought the suggested mic "Kinobo - USB 2.0 Mini Microphone "Makio" Mic for Laptop/Desktop PCs" from the link in the readme ( http://amzn.com/B00IR8R7WQ ) and it is almost worthless, even when I turn off the auto gain and set mainual gain to max with alsamixer.

I'll look at the desktop audio controls that @MrJamesEllis suggested.
