### ISSUE TITLE
Languages support ?

### ISSUE THREAD

**Issue by Tisamu** [amzn/alexa-avs-raspberry-pi#67]
While reading the README, I was thinking about the language support.
I'm french so I would like to know if the Voice support will be in french or something ?

Thanks for answering me and sorry if that's not the place to ask this kind of questions.

**Comment by gregwa1953** [comment]
Currently, from what I can tell, English is the only language that is supported.  There are many people that are guessing as soon as they start selling the device in Mexico/Spain, they will support some version of Spanish.  Once in France, they will support French, etc.

**Comment by Tisamu** [comment]
That's sounds Logic, Thanks for answering !
