### ISSUE TITLE
Please support other languages also

### ISSUE THREAD

**Issue by TylonHH** [amzn/alexa-avs-raspberry-pi#70]
Hi,
I want to try it out. But as an German, can I only use out in English?

**Comment by erikswed** [comment]
Does this work in Sweden? 
I see the Amazon Echo cylinder speaker does not work in Sweden so I guess it's not working

**Comment by gregwa1953** [comment]
Unfortunately, from what I understand, the only language that is supported by Amazon at this point is English.  Once they start selling the Echo/Alexa in other countries (it's not even available in the UK yet), they will support the "official" language of those countries.

**Comment by ajotwani** [comment]
Thanks for your inquiry @TylonHH.  At this time, Alexa Voice Service (AVS) only supports English.

**Comment by erikswed** [comment]
a novice question, if it only support English and i run this from Sweden will it work if I speak English here in me Swedish living room?

**Comment by markbeee** [comment]
It works in Germany with english language so this might be no problem in Sweden either. But there are some restrictions to functionality in comparison to the original Amazon Echo like Bluetooth connectivity, smart home functionality etc.
