### ISSUE TITLE
Activate with clap detector

### ISSUE THREAD

**Issue by loydmilligan** [amzn/alexa-avs-raspberry-pi#72]
I have had a pi sitting around for a year and nothing to do with it - excited that this project solved that problem. Got it working without incident. As others have stated - the ability to activate and use this from anywhere within a room is the only thing that is missing. Would truly make this a replacement for buying an echo. 

After doing a bit of googling - I found this project:

https://www.npmjs.com/package/clap-detector

As I am brand new to this - I thought I would ask the more experienced players here if they thought this would work - before I dove in and tried to figure it out. 

Any thoughts/warnings/tips would be appreciated. 

I read another thread about a physical button - which would be better than current function, but still lacking IMO - any other ideas to solve this problem?

**Comment by bill-orange** [comment]
Perhaps someone knowledgeable in the structure of Alexa can identify the entry point that  loydmilligan wound need to trigger.

•clapDetector.onClap(yourcallbackfunctionhere) => register a callback that will be triggered whenever a clap of hand is detected

**Comment by gabe817** [comment]
I thought a physical button was the only way to activate it.  How are you doing it now?

**Comment by loydmilligan** [comment]
Currently I am using the default behavior for the project, must Click the start/stop listening button on screen.  

Best case scenario would be that it would function identical to an echo (Always listening, respond to a specific phrase). I am guessing that mimicking that would be a tall order.  Barring that, I think the next best thing is something that can be activated by anyone in a room from anywhere in a room.  Clapping would seem to be a good fit. The physical button is still a good idea in that it would eliminate the need to use a monitor and keyboard/mouse - however, the user would still need to move to a specific place in the room to use it.  

@bill-orange - that is exactly what the type of info that would be helpful - which part of the current code deals with the stop/start listening button?

**Comment by gabe817** [comment]
I must have a faulty installation.  I don't have a start/stop listening 
button on screen.  I had assumed the application was running in the 
background and woke up when the button was pressed. Since I wasn't 
hearing anything I thought my problem was with the audio.  Do you have 
to do anything to launch the program or is it supposed to be running on 
boot up?  Does anyone have a screen shot of the application showing the 
start/stop button?

**Comment by bill-orange** [comment]
I do not have a screen shot, unfortunately. I don't think it would help you anyway. I had roughly the same symptoms as you report initially. The problem was my edit of ssl.cnf. Take a look at the sample at the end of the read me. I tried entering my call sign for the common name. I discovered that line has to remain unchanged. The editing of ssl.cnf is apparently really touchy.

**Comment by loydmilligan** [comment]
@gabe817 If you look at the instructions - go to step 10 - that whole step is about installing and starting the application.  there is a screenshot of what the interface should look like on your screen.

**Comment by gabe817** [comment]
I was following a different set of instructions to do the install and I 
thought it was supposed to start running automatically on reboot.  I'll 
try picking up your procedure at step 10 and see if that's what I'm 
missing.  Thanks for the input.

**Comment by kalilay** [comment]
i have an old "clapper" laying around.  im thinking about just connecting up to the relay that gets thrown when it detects a set of claps and use that as the hardware button push.  

dont like messing with the 110vac tho lol

**Comment by MrJamesEllis** [comment]
I was thinking about this as well, could try a littlebits sensor and a cloudbit to send a signal to the Pi and trigger the "Start Listening" event ?

Could possibly do it via the companionService

http://littlebits.cc/shop/bits/sensors
https://littlebits.cc/bits/cloudbit

**Comment by bill-orange** [comment]
I had not seen that cloudbit device before.  That looks pretty useful for all kinds of projects.  Hopefully, we can get some guidance on the location and nature of the "Start Listening" event trigger.  Have a look at issue #39. That may put us in the right direction.  The timing changes I am running discussed in that issue are really helpful.

**Comment by sciencedude100** [comment]
I too would like to add an external start/stop control, I'm building a HAL 9000.

**Comment by loydmilligan** [comment]
So I was able to get clap detection working very easily in the companon service code. simply installed the code and then used the commands listed on that page I linked to.  It was very easy to manipulate the threshold and/or the number of claps. If I understand the way the comp serv code works - the companionservices are used at startup to get the auth and the token. So - it seems clear that the companion service is talking to alexa. So - now that the clap detector is able to work in companion service I just need to know how to send the start and stop recording command. 

I have almost no experience with Java - can someone who knows what they are doing chime in on 1. how to send something from companionservice upon clap detection and 2. where in the main code deals with starting and stopping recording.

This is the code that detects the clap:
// Register on clap event
clapDetector.onClap(function() {
    //console.log('your callback code here ');
}.bind(this));

To me it seems that "function" is the place to add code that sent a button press. I know it was detecting the clap because I un-commented the console.log but above and it printed when I clapped.

Thanks in advance for any help

**Comment by vlasov01** [comment]
@loydmilligan Please take a look at implementation of RequestListener interface in AVSApp.java. I think it will be more efficient if you can share your project.

**Comment by olliegg123** [comment]
@loydmilligan Any advance on the situation?

**Comment by xuchen** [comment]
Sorry for coming late into this discussion. We just released a hotword (or "wake word" as Amazon calls it) detector specifically for voice triggering an action:

https://snowboy.kitt.ai

It has Raspberry Pi support and Python bindings/wrapper (through SWIG). Though no Java wrapper yet:

https://github.com/kitt-ai/snowboy

We'd very much appreciate a pull request for Alexa/Pi integration.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
