### ISSUE TITLE
Frustrated New User Login Password

### ISSUE THREAD

**Issue by phrankc** [amzn/alexa-avs-raspberry-pi#74]
OK so this project was all over the news and looked cool. So I bought all the stuff and followed the directions up to 2.7 Step 3. Logged out, and now can't get back in. Asking for user name and password to get to the desktop, but pi and raspberry don't work. What obvious Noobie mistake am I making?

**Comment by iacos** [comment]
I'm a noobie myself but I suggest you start all over again with the install of the Raspbian. It shouldn't take more than an hour or so. If you follow all the steps from the tutorial it is working.

**Comment by bill-orange** [comment]
I agree with iacos, but the default login is pi with a password of raspberry.  To get to the desktop, use the command startx.

**Comment by phrankc** [comment]
Started over several times. Formatted the card and reloaded everything and started over. Still ending up at the same place

**Comment by bill-orange** [comment]
Okay.  I am not sure I totally understand what is happening.  You get the Noob screen on step 1.3.  You get through 1.4.  It prompts you to reboot.  You reboot.  Do you get the graphic desktop?  If you do, we can give you alternate instructions from there.

**Comment by phrankc** [comment]
Yes, I can get that far. I think the problem is at step 2.4 apt-get update. The update has a default to require a user name / password to login to the desktop. perhaps at that point I need to change the default to avoid the problem?


On Mar 31, 2016, at 1:35 PM, bill-orange <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay. I am not sure I totally understand what is happening. You get the Noob screen on step 1.3. You get through 1.4. It prompts you to reboot. You reboot. Do you get the graphic desktop? If you do, we can give you alternate instructions from there.

-

**Comment by gregwa1953** [comment]
if you are under the 'pi' account, all you should need to do is "sudo
apt-get ...".  If it asks you for a password at that point (normally
doesn't), then type "raspberry".

Worst case, try "sudo su" before you run the "apt-get" line.

**Comment by bill-orange** [comment]
Yup.  My guess is that you are leaving the 'sudo' off'  I think sudo stands for  'superuser do.
After you complete the 2.4 steps you probably want to type exit to get out of superuser mode.  I discovered that in much later steps being in the superuser (root) file locations causes errors. mvn install will not run for instance.  It took me a while to figure that out.

**Comment by gabe817** [comment]
@bill-orange - Another Noobie here that needs some clarification.  My understanding is that using 'sudo' in front of a command only puts you in superuser mode for that one command but using 'sudo su' will keep you in superuser mode until you exit it.  Is that right?

What is the correct way to exit superuser mode?  Is there and 'exit' command or do you have to logoff and logon again?

**Comment by gregwa1953** [comment]
@gabe817 - try 'sudo su'

**Comment by bill-orange** [comment]
The exit command is 'exit'. It is not necessary to log on and off.

**Comment by cwilkes** [comment]
@gabe817 While it is tempting to do a `sudo su -` and be in super-user mode all the time I would highly recommend you don't do that.  Forcing you to type `sudo <command>` when you need to do something as root is there to protect you from accidentally doing something as root that you shouldn't, like remove a bunch of files that aren't owned by the "pi" account.  Also it helps identify commands that you did run as root but should probably be run by the pi account.

The reason you can do sudo <command> without having to type a password is that in the `/etc/sudoers` file has in `pi ALL=(ALL) NOPASSWD: ALL`  Typically that's not set so as to force you to type a password when doing a command as root.  BTW that also shows a use of sudo as
```
root@raspberrypi:~# ls -l /etc/sudoers
-r--r----- 1 root root 697 Apr  2 08:38 /etc/sudoers
```
that file is only readable by root and only root can write to it, as you can imagine if anyone could change that file it would be pure chaos.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
