### ISSUE TITLE
everything went as planned, no audio or terminal response from alexa

### ISSUE THREAD

**Issue by kalilay** [amzn/alexa-avs-raspberry-pi#76]
the install went pretty much as planned until the very end.  i click to ask a question, it registers that its receiving audio, then nothing happens.

could this have to do with certificate error? any ideas on what i can check?

**Comment by StvnLunsford** [comment]
What speaker set up are you using? Are you forcing your audio through the 3.5mm jack? I had the same problem until I followed the instructions [here](https://www.raspberrypi.org/documentation/configuration/audio-config.md) on the Raspberry Pi website.

**Comment by mjt85nc** [comment]
I had that same problem I use my HDMI surround and  had to edit config.  
sudo nano /boot/config.txt
And at the bottom add these lines

#Always force HDMI output and enable HDMI sound

hdmi_force_hotplug=1

hdmi_drive=2



That solved my problem for hdmi

**Comment by kalilay** [comment]
i am using a usb headset because it is the only usb mic i have.  the issue was that when i changed to the USB mic as the sound card it also changed the output and it wouldnt send audio back out over the usb to the headset even though it was registering the mic input.

SOLUTION:

installed pulseaudio and pavucontrol, changed the profile of the headset to "digital stereo input" and then the system saw the headset as a mic only

forced the audio out over hdmi as suggested above and everything worked perfect.
