### ISSUE TITLE
npm start issue missing 

### ISSUE THREAD

**Issue by burtondav** [amzn/alexa-avs-raspberry-pi#78]
When I run `npm start`

![2016-03-31_09-45-21](https://cloud.githubusercontent.com/assets/1197501/14182083/0e5f0cc6-f727-11e5-81e6-748b6b732824.png)

**Comment by StvnLunsford** [comment]
I have a similar problem, but rather than it being node.crt that can't be found, it's node.key - which is weird, since I can see node.key at the exact filepath it says that it can't be found.

**Comment by enjohnson** [comment]
I had the same issue.  Check your SSL.cnf file.  
country and state 2 character only.
I fixed my country name and re-ran generate.sh and files appeared correctly.

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = US                 # C=
stateOrProvinceName     = XX            # ST=
localityName            = YourCity                         # L=
organizationName        = YourNameHere                # O=
organizationalUnitName  = Security          # OU=

**Comment by ajotwani** [comment]
@StvnLunsford here's what the ssl.cnf file would look like, replacing country, state, locality with your respective info - https://gist.github.com/ajotwani/a0d54110a968c984fd0b

**Comment by burtondav** [comment]
Thanks for all the help!  
I updated my ssl.cnf and reran the generate.sh
Now listening on 3000
