### ISSUE TITLE
How is music buffering/caching handled

### ISSUE THREAD

**Issue by itzmrdavis2u** [amzn/alexa-avs-raspberry-pi#79]
when applying to use prime music you need to...
"Please briefly describe your device’s buffering/caching mechanisms"
does anyone know how this is done on the raspberry pi? I was rejected on the first attemp with a response of
You are missing sufficient answers to the following questions: 
          Please briefly describe your device’s buffering/caching mechanisms – local caching of music for more than 10 seconds in not allowed

**Comment by stayupthetree** [comment]
I entered "RaspberryPi 3" and got denied.

**Comment by Democritus90** [comment]
I'm curious if anyone has this working. I enabled Amazon Music ("raspberry pi" for both fields) but Alexa states that Amazon Music isn't enabled on this device.

**Comment by itzmrdavis2u** [comment]
@Pentahex I will try "none" and resubmit and see how it goes. are you a prime member and on a .com account? I am afraid that in order for music to fully work people in the uk on co.uk accounts would have to migrate to a .com account for it to work.
@Democritus90 have you checked to see if you have been approved? If you go to the App page and select the music tab it will sa at the top if it is "pending" or Approved etc.

**Comment by Democritus90** [comment]
@itzmrdavis2u ah, I see, it does still say pending, thanks for the clarification.

**Comment by Democritus90** [comment]
Finally heard back. "Hi. Unfortunately, your recent request to access Amazon Music through the Alexa Voice Service developer preview has been denied." @Pentahex , did you enter "none" for both fields? Did you get music working?

**Comment by itzmrdavis2u** [comment]
@Democritus90 I eventually used "VLC Media Player" for one and "None" for another and both got approved. I would suggest you state none and try again

**Comment by itzmrdavis2u** [comment]
downside for me is you have to have a US prime account for prime music to work but I live in the UK with a co.uk account which is not supported :-1:

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by Democritus90** [comment]
My account was approved using "VLC Media Player" and "None", thanks.
