### ISSUE TITLE
clearer license

### ISSUE THREAD

**Issue by omouse** [amzn/alexa-avs-raspberry-pi#8]
Is the code under the Apache or Eclipse license or MIT? I'm hesitant to look at the code at the moment because it isn't clear if it's a weird open source license or a standard license like MIT or GPL. Thanks!

**Comment by barbeau** [comment]
+1 for Apache v2.0

**Comment by ajotwani** [comment]
License updated - https://github.com/amzn/alexa-avs-raspberry-pi/commit/9fb3c87385b4eb5ee78fb332668ed5c16922f6c6

**Comment by omouse** [comment]
okay so it's definitely not a standard open source license then, cool
