### ISSUE TITLE
I messed up step 10 - how do I recover

### ISSUE THREAD

**Issue by burtondav** [amzn/alexa-avs-raspberry-pi#80]
I got the Step 10 - Obtain Auhorization Login.....
Now when I run `mvn exec:exec I don't get the popup to copy and paste the url

How can I recover?

**Comment by bill-orange** [comment]
I am not clear on the problem.  Did it once work and now it doesn't.  If you have not gotten it work at all then the likely problem is the ssn.cnf file edits. This part of the procedure gave me a lot of trouble.  Your ssl.cnf should look something like the sample.

https://gist.github.com/ajotwani/a0d54110a968c984fd0b

Don't change line 14 at all.

**Comment by StvnLunsford** [comment]
Do you get any error codes when you run mvn exec:exec?

**Comment by burtondav** [comment]
When I run man exec:exec, I don't get:
" When you run the client, a window should pop up with a message that says something similar to:
Please register your device by visiting the following website on any system and following the instructions: https://localhost:3000/provision/d340f629bd685deeff28a917 Hit OK once completed."

Then the app runs and in the console I get `There was a problem connecting to the companion service.`

**Comment by StvnLunsford** [comment]
Make sure you ran the "npm start" command from step 8; that was what the problem connecting to the companion service was referring to when I experienced that issue. If you're connected to the Pi using SSH, I think the popup window will appear in the GUI of the Pi itself. I think you can use "export DISPLAY" to make it pop up on your screen.

**Comment by burtondav** [comment]
Thank you that fixed it.

**Comment by DeltaCharlieAlpha** [comment]
Any other trouble-shooting tips for this problem?  I have reviewed my ssn.cnf file and made sure ran the npm start command, but I still don't get the pop-up.  I am executing it directly on the Pi.  Any other troubleshooting tips?
