### ISSUE TITLE
java.util.concurrent.ExecutionException error

### ISSUE THREAD

**Issue by ds3ctor** [amzn/alexa-avs-raspberry-pi#83]
Greetings,

I am receiving the following error 
![desktop 1_001](https://cloud.githubusercontent.com/assets/18221013/14220905/56ed57be-f820-11e5-86e2-ca9695059ba5.png)
message after asking a question. 

**java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException**

Any suggestions?

**Comment by recklessfb** [comment]
Having the same problem. I also do not hear any audio when I press play. There should be an audio cue right?

**Comment by wedob13** [comment]
how you got it to work though?

**Comment by elstryan** [comment]
@recklessfb and @ds3ctor is it possible to post your application.log from around the time this error occurs?

Also: yes there should be an audio cue when you press the Start Listening button.

**Comment by recklessfb** [comment]
@elstryan Sorry don't have think I can help with the error log.. I managed to fix the error a few minutes after my post hence the edit in my post. 
Iirc, my problem was that my mic volume was too low, I'd suggest playing around with the mic settings.

**Comment by wedob13** [comment]
Guys i have a simple solution to try. As i am not an native english speaker i mixed something up in the instructions. When you get prompt the message saying copy-paste the authorization url, dont forget this simple thing. First you need to login and successfuly get the tokens ready for the device and then press OK to close the pop up. I was doing it wrong. First i pressed okay thinking that is not a big deal and then i logged in to authorize. 

Now it works perfectly. Thanks for everything!

**Comment by ajotwani** [comment]
@wedob13 Thanks for confirming that this works for you now. Closing as resolved.

**Comment by syauqy** [comment]
@wedob13 
I've tried your method to press ok the dialog box first then login. But it doesn't work.
the avs won't start companion service client because it's not authenticated yet.
And the device can't respond my command

would you tell me the method step by step?
