### ISSUE TITLE
How to use a USB Headset as the mic

### ISSUE THREAD

**Issue by kalilay** [amzn/alexa-avs-raspberry-pi#85]
I have no usb mics, but i have a usb headset.  

The client would not send audio to the speaker on the headset, but it accepted the mic input.

To solve the problem i had to change the profile of the headset so the system would see it only as a mic.

install pulseaudio and pavucontrol.  open pulse audio volume control through the menu and go to configuration.  change the profile of your headset to 'digital stereo input'  

done

**Comment by MrMindlink** [comment]
# @kalilay - I have the same situation but when I tried your suggestion it had no effect; any other suggestions?

**Comment by MrMindlink** [comment]
I found a solution here at about 32:10

https://www.youtube.com/watch?v=6fAdBehSYiA&ebc=ANyPxKqmDRAh3TLqdxudYOrZG1miVv6092bcL9yFfNa91iicqacn5AHejenDtLlLOMSSzHsspB40T0PDPbx8oAzEjvemAxrFDQ

My headset now works; speakers and mic

Thanks Tony D!

(RaspberryPi3, Jesse, Plantronics USB headset)

**Comment by doug2311** [comment]
After struggling to do this cleanly with ASLA configs in raspbian "jesse", I gave up and solved this issue by brute force by just not loading the bcm2835 kernel driver for the default internal headphone jack. That way, my USB mic/speaker (Jabra SPEAK 510) is the only audio device.

1. Edit /boot/config.txt and comment out dtparam=audio=on
2. Edit /lib/modprobe.d/aliases.conf and comment out options snd-usb-audio index=-2
3. Reboot your pi

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by cylinderStudio** [comment]
The solution from @doug2311 works for me. Although the Java application reports an error ("cannot obtain source audio line"), my Jabra USB headset works as both an input and output device.

**Comment by tweaty100** [comment]
@doug2311 @cylinderStudio 
what do you mean by comment out do we have to remove this line ?
i am not getting anything in this file its blank what to do please help?
 Thanks

**Comment by mattmacfadyen96** [comment]
I am also having the same issue. When I play the voice client it listens to me and I can see the bar moving but it does not respond to me
