### ISSUE TITLE
./generate.sh not generating a node.crt?

### ISSUE THREAD

**Issue by WalkerGriggs** [amzn/alexa-avs-raspberry-pi#88]
After I run the generate script and look into /certs/server/, I find a node.key and jetty.key, but no node.crt. Is the generate file supposed to take care of this for me?

**Comment by WalkerGriggs** [comment]
For that matter, the ca.crt is not being generated either...

**Comment by kastation** [comment]
I have the same issue, the generate.sh didn't create the certificate, from the console it was showing error of not generating the file.

**Comment by keleric** [comment]
Is this your issue? https://github.com/amzn/alexa-avs-raspberry-pi/issues/108

**Comment by kastation** [comment]
Got passed that issue

**Comment by chalda** [comment]
as with the other thread, it seems i was not the only one that had the issue so it might help to clarify this step a bit in the readme.

**Comment by kastation** [comment]
When u generate the certificate make sure the country code is two
characters long like "US"

**Comment by ajotwani** [comment]
Here's what the ssl.cnf file would look like, replacing country, state, locality with your respective info - https://gist.github.com/ajotwani/a0d54110a968c984fd0b

Closing as resolved.
