### ISSUE TITLE
No Pop-up to obtain authorization from Amazon (step 10)

### ISSUE THREAD

**Issue by deaconblus** [amzn/alexa-avs-raspberry-pi#90]
Ran into a few issues that I think I've been able to solve. But running into difficulties on the home stretch.

After 'mvn exec:exec'; I don't encounter any errors and the Alexa Voice Service window opens but I do not get a prompt to register my device with a URL.  My Bearer Token field is obviously empty as a consequence of me not being able to register the device.

Any suggestions?

**Comment by vlasov01** [comment]
@deaconblus I had a similar issue when I forgot to run compilation. Try to run 
`mvn validate compile`
and then
`mvn -e -X exec:exec`

**Comment by deaconblus** [comment]
Hmm. Thanks for the response, but same symptom. Cannot get the auth box to appear.

**Comment by vlasov01** [comment]
@deaconblus Are there any messages in the log?

**Comment by cwilkes** [comment]
@deaconblus do you do an `npm start` in another window?  You need to have the node app running, but you should see an error in the logs about it.

Are you VNC'ing into your pi?  You need to do that to see the XWindows-like popup to get the URL.

**Comment by deaconblus** [comment]
Thanks again, lots of useful info in this and other threads.

I am VNC'ing in and have a separate terminal tab running the node app, listening on 3000. For clarification, the Java "alexa app" popup does start, but because I don't get the auth popup I have no way of knowing what to enter into the Bearer Token field, so when I push "start listening" it just hangs.

I'll check the log when I get a chance soon to see if anything looks untoward.

**Comment by cwilkes** [comment]
@deaconblus did you complete the app registration on the Alexa website?  That might be one reason the "click on this url" popup doesn't appear. 
I'll look on my installation to see if what files are generated after clicking on the link. Perhaps some of them are there and thus you aren't being prompted to do it again. 
After clicking on the local host link the bearer token will be filled in, you shouldn't have to type in anything there. 
Oh and it also helps to plug in some speakers or a headset to hear the Alexa ready sound and what she repeats back. While that might be obvious it took me some time to figure out why it didn't look like it was working.

**Comment by deaconblus** [comment]
I did complete the registration in the earlier steps, but still no pop-up. 

I'm not getting a local host link pop-up window. Just the main app window popping up. If I click on "Start Listening" I get a sound, I can speak into the mic and then the app will go into 'processing' and just hang there.

**Comment by vlasov01** [comment]
@deaconblus Try to run it as
`mvn -e -X exec:exec`

**Comment by deaconblus** [comment]
@vlasov01 Yup, I've tried that multiple times. Same issue. No pop-up. No real errors generated. Just the "Alexa" app opening but no authorization pop-up.

**Comment by vlasov01** [comment]
@deaconblus Could you please dump the log after executing 
`sudo mvn -e -X exec:exec`
So I can compare it with mine.

**Comment by stanica** [comment]
I had the same issue. Make sure you have the correct version of Java installed and no other conflicting versions.

**Comment by deaconblus** [comment]
Ok. I'm out of my element here, do I have conflicting versions...?
![screen shot 2016-04-07 at 9 28 16 pm](https://cloud.githubusercontent.com/assets/18235246/14372606/bf6a3424-fd07-11e5-8636-eaf2d3043fc1.png)

**Comment by stanica** [comment]
Mine looks like this:
![image](https://cloud.githubusercontent.com/assets/1376740/14373140/febdfc16-fd14-11e5-89c2-fbb7c21a190b.png)

**Comment by MagiCats** [comment]
I have the same problem and would like a solution.

**Comment by HentschelT** [comment]
selecting the correct java version in step 2.6 fixed this for me. Don't use the default that comes with Jessie, select the version that you downloaded and installed when prompted by:

sudo uptdate-alternatives --config javac
sudo uptdate-alternatives --config java

(the default Jessie version isn't correct)

**Comment by ajotwani** [comment]
@deaconblus can you confirm if you're still having this issue?

**Comment by MagiCats** [comment]
I found what was wrong but did not realize that I posted that question.

**Comment by pi0089** [comment]
What was wrong?? :)

**Comment by sidharthrajaram** [comment]
I have the exact same error as well.

**Comment by sidharthrajaram** [comment]
Is the problem still persisting @deaconblus ?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by aaldoori** [comment]
I am having the same problem

**Comment by AdithyanI** [comment]
@deaconblus @aaldoori 
I have the exact same problem. Did you guys solve this?
If yes, how? Please let me know. Thanks for the help.

**Comment by amaster4000** [comment]
Hello, can anyone help? I have the same issue where I get the Alexa Voice Service java application window, but no authorization popup, and my bearer token field is empty. Almost there...

The output of my   mvn -e -X exec:exec
-----------------------------------------------------------------------------------

root@netbook:/opt/alexa-avs-sample-app/samples/javaclient# 
root@netbook:/opt/alexa-avs-sample-app/samples/javaclient# mvn -e -X exec:exec
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-47-generic", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /root/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /root/.m2/toolchains.xml
[DEBUG] Using local repository at /root/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /root/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.amazon.alexa.avs:sample-java-client:jar:20160207.3: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM com.amazon.alexa.avs:sample-java-client:jar:20160207.3
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.amazon.alexa.avs:sample-java-client:jar:20160207.3
[DEBUG] Tasks:   [exec:exec]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM com.amazon.alexa.avs:sample-java-client:jar:20160207.3
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.amazon.alexa.avs:sample-java-client:20160207.3
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <arguments>
    <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar</argument>
    <argument>-Dlog4j.configurationFile=file:////opt/alexa-avs-sample-app/samples/javaclient/log4j2.xml</argument>
    <argument>-classpath</argument>
    <classpath/>
    <argument>-Djna.library.path=${env.VLC_PATH}</argument>
    <argument>com.amazon.alexa.avs.App</argument>
  </arguments>
  <basedir default-value="${basedir}"/>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <executable>java</executable>
  <longClasspath default-value="false">${exec.longClasspath}</longClasspath>
  <outputFile>${exec.outputFile}</outputFile>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
  <skip default-value="false">${skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
  <workingDirectory>${exec.workingdir}</workingDirectory>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=8, ConflictMarker.markTime=2, ConflictMarker.nodeCount=52, ConflictIdSorter.graphTime=2, ConflictIdSorter.topsortTime=2, ConflictIdSorter.conflictIdCount=29, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=32, ConflictResolver.conflictItemCount=51, DefaultDependencyCollector.collectTime=869, DefaultDependencyCollector.transformTime=54}
[DEBUG] com.amazon.alexa.avs:sample-java-client:jar:20160207.3
[DEBUG]    commons-codec:commons-codec:jar:1.9:compile
[DEBUG]    commons-io:commons-io:jar:2.4:compile
[DEBUG]    org.apache.commons:commons-lang3:jar:3.4:compile
[DEBUG]    commons-fileupload:commons-fileupload:jar:1.3.1:compile
[DEBUG]    uk.co.caprica:vlcj:jar:2.4.1:compile
[DEBUG]       net.java.dev.jna:jna:jar:3.5.2:compile
[DEBUG]       net.java.dev.jna:platform:jar:3.5.2:compile
[DEBUG]    org.glassfish:javax.json:jar:1.0.4:compile
[DEBUG]    javazoom:jlayer:jar:1.0.1:compile
[DEBUG]    org.mortbay.jetty.alpn:alpn-boot:jar:8.1.11.v20170118:compile
[DEBUG]    org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[DEBUG]       org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[DEBUG]    org.slf4j:slf4j-api:jar:1.7.10:compile
[DEBUG]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile
[DEBUG]       org.apache.logging.log4j:log4j-api:jar:2.3:compile
[DEBUG]    org.apache.logging.log4j:log4j-core:jar:2.3:compile
[DEBUG]    org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile
[DEBUG]    javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=3, ConflictMarker.markTime=3, ConflictMarker.nodeCount=68, ConflictIdSorter.graphTime=3, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=25, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=4, ConflictResolver.conflictItemCount=65, DefaultDependencyCollector.collectTime=432, DefaultDependencyCollector.transformTime=14}
[DEBUG] org.codehaus.mojo:exec-maven-plugin:jar:1.2.1:
[DEBUG]    org.apache.maven:maven-toolchain:jar:1.0:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-model:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact-manager:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-core:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6:compile
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile
[DEBUG]       org.apache.maven:maven-error-diagnostics:jar:2.0.6:compile
[DEBUG]       commons-cli:commons-cli:jar:1.0:compile
[DEBUG]       org.apache.maven:maven-plugin-descriptor:jar:2.0.6:compile
[DEBUG]       org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.0.6:compile
[DEBUG]       classworlds:classworlds:jar:1.1:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:2.0.5:compile
[DEBUG]    org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile
[DEBUG]       junit:junit:jar:3.8.2:test
[DEBUG]    org.apache.commons:commons-exec:jar:1.1:compile
[DEBUG] Created new class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Included: org.codehaus.mojo:exec-maven-plugin:jar:1.2.1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.0.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7
[DEBUG]   Included: commons-cli:commons-cli:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:2.0.5
[DEBUG]   Included: org.apache.commons:commons-exec:jar:1.1
[DEBUG] Configuring mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:exec from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1, parent: sun.misc.Launcher$AppClassLoader@55f96302]
[DEBUG] Configuring mojo 'org.codehaus.mojo:exec-maven-plugin:1.2.1:exec' with basic configurator -->
[DEBUG]   (f) arguments = [-Xbootclasspath/p:/root/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar, -Dlog4j.configurationFile=file:////opt/alexa-avs-sample-app/samples/javaclient/log4j2.xml, -classpath, Classpath {}, -Djna.library.path=${env.VLC_PATH}, com.amazon.alexa.avs.App]
[DEBUG]   (f) basedir = /opt/alexa-avs-sample-app/samples/javaclient
[DEBUG]   (f) classpathScope = runtime
[DEBUG]   (f) executable = java
[DEBUG]   (f) longClasspath = false
[DEBUG]   (f) project = MavenProject: com.amazon.alexa.avs:sample-java-client:20160207.3 @ /opt/alexa-avs-sample-app/samples/javaclient/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@3deb2326
[DEBUG]   (f) skip = false
[DEBUG] -- end configuration --
[DEBUG] Collected project artifacts [commons-codec:commons-codec:jar:1.9:compile, commons-io:commons-io:jar:2.4:compile, org.apache.commons:commons-lang3:jar:3.4:compile, commons-fileupload:commons-fileupload:jar:1.3.1:compile, uk.co.caprica:vlcj:jar:2.4.1:compile, net.java.dev.jna:jna:jar:3.5.2:compile, net.java.dev.jna:platform:jar:3.5.2:compile, org.glassfish:javax.json:jar:1.0.4:compile, javazoom:jlayer:jar:1.0.1:compile, org.mortbay.jetty.alpn:alpn-boot:jar:8.1.11.v20170118:compile, org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile, org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile, org.slf4j:slf4j-api:jar:1.7.10:compile, org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile, org.apache.logging.log4j:log4j-api:jar:2.3:compile, org.apache.logging.log4j:log4j-core:jar:2.3:compile, org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile, javax.servlet:javax.servlet-api:jar:3.1.0:compile]
[DEBUG] Collected project classpath [/opt/alexa-avs-sample-app/samples/javaclient/target/classes]
[DEBUG] dealing with commons-codec:commons-codec:jar:1.9:compile
[DEBUG] dealing with commons-io:commons-io:jar:2.4:compile
[DEBUG] dealing with org.apache.commons:commons-lang3:jar:3.4:compile
[DEBUG] dealing with commons-fileupload:commons-fileupload:jar:1.3.1:compile
[DEBUG] dealing with uk.co.caprica:vlcj:jar:2.4.1:compile
[DEBUG] dealing with net.java.dev.jna:jna:jar:3.5.2:compile
[DEBUG] dealing with net.java.dev.jna:platform:jar:3.5.2:compile
[DEBUG] dealing with org.glassfish:javax.json:jar:1.0.4:compile
[DEBUG] dealing with javazoom:jlayer:jar:1.0.1:compile
[DEBUG] dealing with org.mortbay.jetty.alpn:alpn-boot:jar:8.1.11.v20170118:compile
[DEBUG] dealing with org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[DEBUG] dealing with org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[DEBUG] dealing with org.slf4j:slf4j-api:jar:1.7.10:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-api:jar:2.3:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-core:jar:2.3:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with javax.servlet:javax.servlet-api:jar:3.1.0:compile
[DEBUG] Executing command line: java -Xbootclasspath/p:/root/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar -Dlog4j.configurationFile=file:////opt/alexa-avs-sample-app/samples/javaclient/log4j2.xml -classpath /opt/alexa-avs-sample-app/samples/javaclient/target/classes:/root/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/root/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/root/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/root/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar:/root/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar:/root/.m2/repository/net/java/dev/jna/jna/3.5.2/jna-3.5.2.jar:/root/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar:/root/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/root/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar:/root/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/root/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar:/root/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar:/root/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar:/root/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar:/root/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar:/root/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar -Djna.library.path=${env.VLC_PATH} com.amazon.alexa.avs.App
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2017-05-15T15:19:25-04:00
[INFO] Final Memory: 14M/160M
[INFO] ------------------------------------------------------------------------

**Comment by karthikcoool** [comment]
even im facing a similar problem,
i have followed all the steps but the pop up window not appearing,,
can anyone help me?

**Comment by tholler3012** [comment]
Maybe I have a solution - but first I have a question:
Is it right, at step 10, when the java-popup appears, that on the top besides Device and DSN is standing "NO NOTIFICATIONS"?
If that is a fault, how can I correct that - and perhaps the second Popup will appear.

Regards
Thorsten

**Comment by karthikcoool** [comment]
thank you for replying , 
but after that i loaded google assistant libraries , and my pi became mini google home, 
infact google is easier to install than alexa in raspberry pi( as in my case)..............

**Comment by TheGreatBorg** [comment]
SOLVED! 

**Start Terminal 1: companion service**  
cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService && npm start

**Then start Terminal 2: Where you test a given ALPN versionen**
Go to the JAVA client folder and write (mvn exec:exec -Dalpn-boot.version=YOUR_VERSION):

cd /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient 
mvn exec:exec -Dalpn-boot.version=8.1.12.v20180117

If the pop-up works you will have to correct the versions in your pom.xml file in the java client folder

![image](https://user-images.githubusercontent.com/31419036/35476227-9e57af52-03ac-11e8-8bc5-a28e1063def7.png)

![image](https://user-images.githubusercontent.com/31419036/35476232-aa91cfdc-03ac-11e8-8669-dedd05e55935.png)

Check the version on your Raspberry Pi. Run:
java -version

![image](https://user-images.githubusercontent.com/31419036/35476247-e3acabac-03ac-11e8-8320-9e2684c9588c.png)

Then look at this page to find java version vs. ALPN version:

http://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-versions

![image](https://user-images.githubusercontent.com/31419036/35476257-031b0c5e-03ad-11e8-9b87-8c0f95319482.png)
