### ISSUE TITLE
how to make the pi+alexa always listening like the echo ?

### ISSUE THREAD

**Issue by iamxuxiao** [amzn/alexa-avs-raspberry-pi#91]
First of all, great tutorial ! I was able to get everything working in three hours including all the installing and registration !  Thanks ! it was very fun. 

now question : 

In the javaclient example , one has to click the button to make the device starts to listening , and then speak to the device. Is it possible to make it listening all the time and activated it by saying "Alexa", just like what the echo do ?

**Comment by loydmilligan** [comment]
Totally agree, if this could replace an echo it needs to be able to be activated from anywhere in a room. I fear that voice detection might be a tall order, so I am trying to use some clap detection code I found. I will update this thread if/when I figure it out:
https://github.com/amzn/alexa-avs-raspberry-pi/issues/72

**Comment by joetech** [comment]
I'm also looking into doing this with voice and a trigger word.  I'll update if I get anything working.

**Comment by cwinnbari** [comment]
http://diyhacking.com/best-voice-recognition-software-for-raspberry-pi/

Anyway to use this to get a voice activation to start Alexa?

**Comment by pomeroythomas** [comment]
If you'd have read any of what you were clicking through on Amazon's developer page, you'd know that the pushbutton is a necessary requirement imposed by Amazon.

**Comment by markbeee** [comment]
I wouldn't say that - it's possible to get some hardware and do the invocation by that piece of electronics. There is a lot of such stuff out there.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by datatypevoid** [comment]
So what's the state of this issue now? I too am interested in an always on-version of the Alexa Pi.
