### ISSUE TITLE
2.6 Install Java Development Kit?  Which file is it? also, Pi3 64bit?

### ISSUE THREAD

**Issue by MrMindlink** [amzn/alexa-avs-raspberry-pi#92]
The file, jdk-8u77-linux-arm32-vfp-hflt.tar.gz, is listed on Oracle's site like this:

"Linux ARM 32 **Soft Float** ABI **77.7 MB**   jdk-8u77-linux-arm32-vfp-hflt.tar.gz "

"Soft Float" 

The instruction read "**Hard Float**" which is listed like this on Oracle's site:

Linux ARM 32 **Hard Float** ABI  **9.95 MB**  jdk-8u77-linux-arm32-vfp-hflt-demos.tar.gz 

Which one do I need?

Also, Pi3 is 64bit, should I be using the 64bit version? and if so, which one exactly?

Thanks

FOR REFERENCE:

"2.6 Install Java Development Kit

You need to have Java Development Kit (JDK) version 8 or higher installed on the Raspberry Pi. 

Step 1: Download JDK Assuming this is a fresh Raspberry Pi and you do not already have JDK installed, you'll need to download JDK 8 from Oracle. 

Download the tar.gz file listed for Linux ARM 32 **Hard Float** ABI from the Oracle link above. At the time of this writing, the name of this file is **jdk-8u77-linux-arm32-vfp-hflt.tar.gz**.

NOTE: Although there is a 64-bit ARMv8 that Apple and some other smartphones use, there are no raspberry 64-bit ARM processors on pis yet. More info: Raspberry Pi Blog.com"

**Comment by gunner2398** [comment]
I can tell what I did (and it worked).  On the oracle site it seems to me the first one called 'Soft Float' is mislabled.  Note that the file name of the 'Soft Float' ends in 'hflt.tar.gz'.  I used this one.  The file name matches the one in the instructions.

The Demos one doesn't work and I believe it has a different file structure.

Also use the 32 bit, this is spelled out somewhere but I can't recall where.

Hope that helps.

**Comment by MrMindlink** [comment]
gunner2398 - Thanks for the response, that is the file I loaded I just needed some conformation; the whole hard/soft float thing had me going...  they should fix the instructions.  Thanks.

**Comment by ajotwani** [comment]
Looks like Oracle has renamed the file from Hard Float to Soft Float. Instructions updated https://github.com/amzn/alexa-avs-raspberry-pi/commit/5d3cdd8a38f934e5d5c9831ab0cf77c29d7d280a.

**Comment by MrMindlink** [comment]
Thank you


CRC
