### ISSUE TITLE
npm errors

### ISSUE THREAD

**Issue by StephenWeston** [amzn/alexa-avs-raspberry-pi#97]
getting errors when I use npm start. have tried everything I can think of, including reading what others have done with similar errors.
see below

pi@raspberrypi:~/alexa-avs-raspberry-pi/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-raspberry-pi/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/alexa-avs-raspberry-pi/samples/companionService/app.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/alexa-avs-raspberry-pi/samples/companionService/npm-debug.log
pi@raspberrypi:~/alexa-avs-raspberry-pi/samples/companionService $

**Comment by cwilkes** [comment]
From the error
```
Error: Cannot find module 'express'
```
it looks like `npm install` was not run ... can you show the output of `npm list`?  It will show all your packages installed, post that list in here (and triple backticks around it, see https://guides.github.com/features/mastering-markdown/ ) .  In mine I have `express@4.12.4`

**Comment by StephenWeston** [comment]
This is what npm list. I see express@4.12.4 I am a complete noob working with linux so you may need to spell things out step by step. Thanks for the help.

[[[
pi@raspberrypi:~ $ npm list
/home/pi
└─┬ alexa-voice-service-sample-companion-service@1.0.0
  ├─┬ body-parser@1.12.4
  │ ├── bytes@1.0.0
  │ ├── content-type@1.0.1
  │ ├── depd@1.0.1
  │ ├── iconv-lite@0.4.8
  │ ├─┬ on-finished@2.2.1
  │ │ └── ee-first@1.1.0
  │ ├── qs@2.4.2
  │ ├─┬ raw-body@2.0.2
  │ │ └── bytes@2.1.0
  │ └─┬ type-is@1.6.12
  │   ├── media-typer@0.3.0
  │   └─┬ mime-types@2.1.10
  │     └── mime-db@1.22.0
  ├─┬ debug@2.2.0
  │ └── ms@0.7.1
  ├─┬ express@4.12.4
  │ ├─┬ accepts@1.2.13
  │ │ ├─┬ mime-types@2.1.10
  │ │ │ └── mime-db@1.22.0
  │ │ └── negotiator@0.5.3
  │ ├── content-disposition@0.5.0
  │ ├── content-type@1.0.1
  │ ├── cookie@0.1.2
  │ ├── cookie-signature@1.0.6
  │ ├── depd@1.0.1
  │ ├── escape-html@1.0.1
  │ ├─┬ etag@1.6.0
  │ │ └── crc@3.2.1
  │ ├── finalhandler@0.3.6
  │ ├── fresh@0.2.4
  │ ├── merge-descriptors@1.0.0
  │ ├── methods@1.1.2
  │ ├─┬ on-finished@2.2.1
  │ │ └── ee-first@1.1.0
  │ ├── parseurl@1.3.1
  │ ├── path-to-regexp@0.1.3
  │ ├─┬ proxy-addr@1.0.10
  │ │ ├── forwarded@0.1.0
  │ │ └── ipaddr.js@1.0.5
  │ ├── qs@2.4.2
  │ ├── range-parser@1.0.3
  │ ├─┬ send@0.12.3
  │ │ ├── destroy@1.0.3
  │ │ ├── mime@1.3.4
  │ │ └── ms@0.7.1
  │ ├── serve-static@1.9.3
  │ ├─┬ type-is@1.6.12
  │ │ ├── media-typer@0.3.0
  │ │ └─┬ mime-types@2.1.10
  │ │   └── mime-db@1.22.0
  │ ├── utils-merge@1.0.0
  │ └── vary@1.0.1
  └── node-uuid@1.4.1
]]]

**Comment by scova0** [comment]
Hye

I have the same problem

Have you found a solution ?

**Comment by laurentpi** [comment]
Hello, Same issue here. Can't find the solution.

**Comment by Ikol18** [comment]
when I run npm start it's showing as below ..please helep
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.


/home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService/config.js:26
    products: {
    ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService/authentication.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www

**Comment by keleric** [comment]
It seems as though your config.js file is not valid js/json. Is there a comma on the line above products?

**Comment by sidharthrajaram** [comment]
I have the same error as well.
I tried "npm install express" and tried "npm start again, but then I got this error:
<img width="747" alt="screen shot 2016-06-22 at 6 07 59 pm" src="https://cloud.githubusercontent.com/assets/14987538/16288771/4f289fec-38a4-11e6-9d2f-e8aa21c44744.png">

**Comment by sidharthrajaram** [comment]
My error was solved. The problem was that I didn't reference companionService to my config.json file.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by JeffHoover** [comment]
What do you mean, "I didn't reference companionService to my config.json file" @sidharthrajaram ?

**Comment by vaibhavbhanawat01** [comment]
@JeffHoover and @sidharthrajaram  have you found the solution for this issue ??

**Comment by sidharthrajaram** [comment]
@JeffHoover @vaibhavbhanawat01 Sorry for the late response, I ended up abandoning ship and moving to Google Voice API and CMUSphinx, but what I was referring to was the config.json file that looked a little something like this: 

<img width="402" alt="screen shot 2017-07-30 at 12 01 00 am" src="https://user-images.githubusercontent.com/14987538/28751378-9915f43a-74ba-11e7-9342-c4bb48f1805a.png">

But I believe the latest tutorials and walkthroughs from AVS have eliminated these human-error intensive procedures in favor of an automatic installation script, so hopefully, we won't have to deal with this step again.

**Comment by vaibhavbhanawat01** [comment]
No problem @sidharthrajaram i had already resolve the issue.There was a proxy issue.
