### ISSUE TITLE
Getting "Child" error

### ISSUE THREAD

**Issue by Big-Sally** [amzn/alexa-avs-raspberry-pi#98]
I am having trouble extracting sudo tar zxvf jdk-8u77-linux-arm32-vfp-hflt.tar.gz -C /opt. I get a child error. 

When I try to extract the files directly from the download folder to the opt folder i get a message saying that i don't have permission and i need a password. Anyone know the password? I tried raspberry - no luck.

Help

**Comment by rgdarkchild** [comment]
i was literally just having the same issue you have to go to the downloads folder in terminal so 
cd /home/pi/Downloads
then you can run sudo tar zxvf jdk-8u77-linux-arm32-vfp-hflt.tar.gz -C /opt.

**Comment by rgdarkchild** [comment]
Also the file it tells you to download is wrong it's supposed to be the Soft not hard ;)

**Comment by Big-Sally** [comment]
Thanks. I just shut down to watch NCAA game. But I'll keep in touch. Thanks again.

**Comment by Big-Sally** [comment]
Thanks again.
