### ISSUE TITLE
2.7 Install Maven

### ISSUE THREAD

**Issue by rgdarkchild** [amzn/alexa-avs-raspberry-pi#99]
OK so i did step one and 2 but step 3 is kicking my butt i dont know what im doing wrong 

Help!?!?

Step 3: Tell your shell where to find maven You’ll do this in the system profile settings so it is available to all users.

Create a new file /etc/profile.d/maven.sh, and type the following inside it:

export M2_HOME=/opt/apache-maven-3.3.9
export PATH=$PATH:$M2_HOME/bin
Save the file. Log out and back into the Raspberry Pi so the profile script takes effect. You can test that it is working with the following command:

mvn -version

**Comment by danhannigan** [comment]
I'm a little new to this myself, but the .sh file you create might not be executable when it needs to be (you can check it's permissions first) if it's not try this in terminal: 

`sudo chmod +x /etc/profile.d/maven.sh`

Then of course log out/in or restart and try mvn -version, also double check for typos.

**Comment by cwilkes** [comment]
@rgdarkchild can you post what exactly what you're seeing when you type `mvn -version` ?  For me:

```
pi@raspberrypi:~ $ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.1.19-v7+", arch: "arm", family: "unix"
```

Are you having trouble creating the maven.sh file?  you have to be root to create it, so do a `sudo vi /etc/profile.d/maven.sh` .  Checking the other files in there with a `ls -l /etc/profile.d/maven.sh` shows that it just has to be readable by anyone that's going to use it (permission 644), which it is by default.

**Comment by rgdarkchild** [comment]
i actually got this part working 

![screen shot 2016-04-05 at 12 46 12 am](https://cloud.githubusercontent.com/assets/18274362/14271527/ff3f6444-fac7-11e5-992c-41145c2baf41.png)

**Comment by cwilkes** [comment]
@rgdarkchild can you post what exactly your issue is?  Hard to tell from your original post ...

**Comment by abunaiM4** [comment]
I'm also having an issue with writing the maven.sh file to /etc/usr/profile.d/

I tried using 'sudo vi maven.sh', but vi doesn't seem to want to write the file. 
It says 'No write since last change (add ! to override)

It's been a long time since I've used vi, so it's probably something simple. I also tried using nano, but wasn't able to write the file.

Is it a permissions issue with the directory? I thought using sudo would fix that?

**Comment by Pentahex** [comment]
I think you want /etc/profile.d/maven.sh, not /etc/usr/profile.d/maven.sh

**Comment by abunaiM4** [comment]
@Pentahex True enough. I mistyped the directory in the post, but not on my device. ( I've updated my post above )

**Comment by Pentahex** [comment]
Yeah,

That's why I use nano, the commands are listed so I don't have to remember :-)

**Comment by ajotwani** [comment]
Closing as resolved.
